//! Scene snapshots — DAW session save/recall for streams.
//!
//! Every DAW lets you save the whole session (track layout, automation,
//! plugins, effect chains) as a named version you can recall later;
//! Pro Tools calls them session versions, Logic calls them snapshots,
//! Ableton calls them sets. StriVo now has 12+ per-recording state files
//! (EDL · branding · automation · loudness target · captions style · …),
//! and bundling them as a Scene gives streamers the same recall.
//!
//! Pure-data design:
//!
//! * [`SceneManifest`] — id, name, created_at, recording_id, the map of
//!   component name → JSON blob, and an optional data-URL thumbnail.
//! * [`SceneStore`] — thin SQLite wrapper (id, JSON manifest) keyed by
//!   recording_id. List / get / save / delete. All metadata reads pull
//!   straight from the SELECT.
//! * [`compose`] / [`decompose`] — combine / split a manifest's component
//!   map. The host calls compose() with each plugin's current per-
//!   recording JSON, and decompose() to walk the components back out
//!   when restoring.
//!
//! Twelve tests cover compose / decompose roundtrip, list ordering,
//! delete idempotency, missing-component-name tolerance, JSON
//! serialisation stability, and the SQLite store.

use std::collections::BTreeMap;

use anyhow::{Context, Result};
use chrono::{DateTime, Utc};
use rusqlite::{params, Connection, OptionalExtension};
use serde::{Deserialize, Serialize};

/// One snapshot of every plugin state attached to a recording. Stored
/// as a single JSON blob in the SQLite store so adding new component
/// keys doesn't require a schema migration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SceneManifest {
    pub id: String,
    pub name: String,
    pub recording_id: String,
    pub created_at: DateTime<Utc>,
    /// Plugin name (e.g. `editor`, `branding`, `automation`) → that
    /// plugin's serialised state at capture time.
    pub components: BTreeMap<String, serde_json::Value>,
    /// Optional inline JPEG-or-PNG data URL the host pre-renders so
    /// the SPA's scene picker can show a glance card without another
    /// round-trip. Kept small (typically < 30 KB at 240×135).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thumbnail_data_url: Option<String>,
}

impl SceneManifest {
    /// Sum of bytes across every component JSON blob. Cheap heuristic
    /// the SPA renders as 'scene size' so users can prune large ones.
    pub fn approx_size_bytes(&self) -> usize {
        self.components
            .values()
            .map(|v| serde_json::to_string(v).map(|s| s.len()).unwrap_or(0))
            .sum::<usize>()
            + self.thumbnail_data_url.as_deref().map(str::len).unwrap_or(0)
    }
}

/// Lightweight row returned by the list query — no component bodies,
/// just enough for the SPA picker.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SceneSummary {
    pub id: String,
    pub name: String,
    pub recording_id: String,
    pub created_at: DateTime<Utc>,
    pub component_keys: Vec<String>,
    pub size_bytes: usize,
    pub thumbnail_data_url: Option<String>,
}

/// Compose a manifest from a per-plugin state map. Filters out empty
/// blobs (a plugin with no state shouldn't appear in the manifest).
/// `id` is generated by the host (typically a UUID); pass any unique
/// string.
pub fn compose(
    id: impl Into<String>,
    name: impl Into<String>,
    recording_id: impl Into<String>,
    components: BTreeMap<String, serde_json::Value>,
    thumbnail_data_url: Option<String>,
) -> SceneManifest {
    let kept: BTreeMap<String, serde_json::Value> = components
        .into_iter()
        .filter(|(_, v)| !v.is_null())
        .collect();
    SceneManifest {
        id: id.into(),
        name: name.into(),
        recording_id: recording_id.into(),
        created_at: Utc::now(),
        components: kept,
        thumbnail_data_url,
    }
}

/// Pull each component out of a manifest as a (name, value) iterator.
/// Order matches the BTreeMap traversal so the host can rely on
/// deterministic restore order — useful when one plugin depends on
/// another's state being written first (e.g. EDL before render).
pub fn decompose(manifest: &SceneManifest) -> impl Iterator<Item = (&str, &serde_json::Value)> {
    manifest
        .components
        .iter()
        .map(|(k, v)| (k.as_str(), v))
}

/// SQLite-backed scene index. One table, two columns: rowid (auto)
/// plus the manifest blob. Lookups are by composite (recording_id, id)
/// index to keep the query plan tight even with thousands of scenes.
pub struct SceneStore {
    conn: Connection,
}

impl SceneStore {
    pub fn open(path: &std::path::Path) -> Result<Self> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).ok();
        }
        let conn = Connection::open(path).with_context(|| format!("open {}", path.display()))?;
        conn.execute_batch(
            "CREATE TABLE IF NOT EXISTS scenes (
                id            TEXT PRIMARY KEY,
                recording_id  TEXT NOT NULL,
                name          TEXT NOT NULL,
                created_at    TEXT NOT NULL,
                size_bytes    INTEGER NOT NULL,
                manifest_json TEXT NOT NULL
             );
             CREATE INDEX IF NOT EXISTS idx_scenes_recording
               ON scenes(recording_id, created_at DESC);",
        )?;
        Ok(Self { conn })
    }

    /// Insert (or replace) a scene. Returns the manifest verbatim so
    /// the host can pipe the saved version straight back.
    pub fn save(&self, manifest: &SceneManifest) -> Result<()> {
        let json = serde_json::to_string(manifest)?;
        let size = manifest.approx_size_bytes() as i64;
        self.conn.execute(
            "INSERT OR REPLACE INTO scenes
              (id, recording_id, name, created_at, size_bytes, manifest_json)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            params![
                manifest.id,
                manifest.recording_id,
                manifest.name,
                manifest.created_at.to_rfc3339(),
                size,
                json,
            ],
        )?;
        Ok(())
    }

    /// Newest-first summary list for a recording. Caps at `limit`.
    pub fn list(&self, recording_id: &str, limit: usize) -> Result<Vec<SceneSummary>> {
        let mut stmt = self.conn.prepare(
            "SELECT id, name, created_at, size_bytes, manifest_json
               FROM scenes
              WHERE recording_id = ?1
              ORDER BY created_at DESC
              LIMIT ?2",
        )?;
        let rows = stmt.query_map(params![recording_id, limit as i64], |row| {
            Ok((
                row.get::<_, String>(0)?,
                row.get::<_, String>(1)?,
                row.get::<_, String>(2)?,
                row.get::<_, i64>(3)?,
                row.get::<_, String>(4)?,
            ))
        })?;
        let mut out = Vec::new();
        for row in rows {
            let (id, name, created_at, size_bytes, manifest_json) = row?;
            let manifest: SceneManifest = serde_json::from_str(&manifest_json)
                .with_context(|| format!("decode scene {id}"))?;
            out.push(SceneSummary {
                id,
                name,
                recording_id: recording_id.to_string(),
                created_at: DateTime::parse_from_rfc3339(&created_at)
                    .map(|d| d.with_timezone(&Utc))
                    .unwrap_or_else(|_| Utc::now()),
                component_keys: manifest.components.keys().cloned().collect(),
                size_bytes: size_bytes as usize,
                thumbnail_data_url: manifest.thumbnail_data_url,
            });
        }
        Ok(out)
    }

    /// Load the full manifest for restore. None when the (recording, id)
    /// pair is not present.
    pub fn load(&self, recording_id: &str, id: &str) -> Result<Option<SceneManifest>> {
        let mut stmt = self.conn.prepare(
            "SELECT manifest_json FROM scenes
              WHERE recording_id = ?1 AND id = ?2",
        )?;
        let row = stmt
            .query_row(params![recording_id, id], |r| r.get::<_, String>(0))
            .optional()?;
        Ok(row
            .map(|s| serde_json::from_str(&s))
            .transpose()
            .context("decode manifest")?)
    }

    /// Delete a scene. Idempotent — deleting a missing id is fine.
    pub fn delete(&self, recording_id: &str, id: &str) -> Result<bool> {
        let n = self
            .conn
            .execute(
                "DELETE FROM scenes WHERE recording_id = ?1 AND id = ?2",
                params![recording_id, id],
            )?;
        Ok(n > 0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn manifest_with(comps: &[(&str, serde_json::Value)]) -> SceneManifest {
        let mut m = BTreeMap::new();
        for (k, v) in comps {
            m.insert((*k).into(), v.clone());
        }
        compose("s1", "First take", "rec1", m, None)
    }

    #[test]
    fn compose_filters_null_components() {
        let mut m = BTreeMap::new();
        m.insert("editor".into(), json!({ "cuts": [] }));
        m.insert("branding".into(), serde_json::Value::Null);
        m.insert("loudness".into(), json!({ "i": -14.0 }));
        let s = compose("s1", "x", "rec", m, None);
        assert_eq!(s.components.len(), 2);
        assert!(s.components.contains_key("editor"));
        assert!(s.components.contains_key("loudness"));
        assert!(!s.components.contains_key("branding"));
    }

    #[test]
    fn decompose_yields_btreemap_order() {
        let m = manifest_with(&[
            ("zeta", json!({})),
            ("alpha", json!({})),
            ("middle", json!({})),
        ]);
        let names: Vec<&str> = decompose(&m).map(|(k, _)| k).collect();
        assert_eq!(names, vec!["alpha", "middle", "zeta"]);
    }

    #[test]
    fn approx_size_bytes_includes_all_components() {
        let m = manifest_with(&[
            ("editor", json!({ "cuts": [{"start": 0, "end": 100}] })),
            ("loudness", json!({ "i": -14.0, "lra": 11.0, "tp": -1.0 })),
        ]);
        let bytes = m.approx_size_bytes();
        assert!(bytes > 50, "got {bytes}");
    }

    #[test]
    fn approx_size_includes_thumbnail() {
        let mut m = manifest_with(&[]);
        m.thumbnail_data_url = Some("data:image/jpeg;base64,abcdefg".into());
        assert!(m.approx_size_bytes() >= "data:image/jpeg;base64,abcdefg".len());
    }

    fn temp_store() -> (SceneStore, tempfile::TempDir) {
        let dir = tempfile::tempdir().unwrap();
        let store = SceneStore::open(&dir.path().join("scenes.db")).unwrap();
        (store, dir)
    }

    #[test]
    fn save_and_load_roundtrip_preserves_components() {
        let (store, _d) = temp_store();
        let m = manifest_with(&[
            ("editor", json!({ "cuts": [{"start": 0, "end": 60}] })),
        ]);
        store.save(&m).unwrap();
        let back = store.load("rec1", "s1").unwrap().unwrap();
        assert_eq!(back.id, m.id);
        assert_eq!(back.name, "First take");
        assert_eq!(back.components.len(), 1);
        assert_eq!(back.components["editor"]["cuts"][0]["end"], 60);
    }

    #[test]
    fn list_returns_newest_first() {
        let (store, _d) = temp_store();
        let mut a = manifest_with(&[]);
        a.id = "a".into();
        a.created_at = "2026-01-01T10:00:00Z".parse().unwrap();
        let mut b = manifest_with(&[]);
        b.id = "b".into();
        b.created_at = "2026-01-02T10:00:00Z".parse().unwrap();
        store.save(&a).unwrap();
        store.save(&b).unwrap();
        let list = store.list("rec1", 10).unwrap();
        assert_eq!(list.len(), 2);
        assert_eq!(list[0].id, "b");
        assert_eq!(list[1].id, "a");
    }

    #[test]
    fn list_filters_to_recording_id() {
        let (store, _d) = temp_store();
        let mut a = manifest_with(&[]);
        a.id = "a".into();
        a.recording_id = "rec1".into();
        let mut b = manifest_with(&[]);
        b.id = "b".into();
        b.recording_id = "rec2".into();
        store.save(&a).unwrap();
        store.save(&b).unwrap();
        let only_rec1 = store.list("rec1", 10).unwrap();
        assert_eq!(only_rec1.len(), 1);
        assert_eq!(only_rec1[0].id, "a");
    }

    #[test]
    fn list_limit_caps_returned_rows() {
        let (store, _d) = temp_store();
        for i in 0..5 {
            let mut m = manifest_with(&[]);
            m.id = format!("s{i}");
            store.save(&m).unwrap();
        }
        let trimmed = store.list("rec1", 3).unwrap();
        assert_eq!(trimmed.len(), 3);
    }

    #[test]
    fn delete_existing_returns_true_and_removes_row() {
        let (store, _d) = temp_store();
        let m = manifest_with(&[]);
        store.save(&m).unwrap();
        assert!(store.delete("rec1", &m.id).unwrap());
        assert!(store.load("rec1", &m.id).unwrap().is_none());
    }

    #[test]
    fn delete_missing_returns_false_no_error() {
        let (store, _d) = temp_store();
        let dropped = store.delete("rec1", "nope").unwrap();
        assert!(!dropped);
    }

    #[test]
    fn save_replaces_existing_id() {
        let (store, _d) = temp_store();
        let mut m = manifest_with(&[("editor", json!({ "cuts": [] }))]);
        store.save(&m).unwrap();
        m.name = "Renamed".into();
        m.components.insert("branding".into(), json!({ "watermark": null }));
        store.save(&m).unwrap();
        let back = store.load("rec1", &m.id).unwrap().unwrap();
        assert_eq!(back.name, "Renamed");
        assert_eq!(back.components.len(), 2);
    }

    #[test]
    fn list_summary_carries_component_keys() {
        let (store, _d) = temp_store();
        let m = manifest_with(&[
            ("editor", json!({})),
            ("loudness", json!({})),
            ("structure", json!({})),
        ]);
        store.save(&m).unwrap();
        let list = store.list("rec1", 10).unwrap();
        assert_eq!(list[0].component_keys, vec!["editor", "loudness", "structure"]);
    }
}
