use std::collections::{HashMap, HashSet};
use std::path::PathBuf;

use ratatui_image::picker::Picker;
use ratatui_image::protocol::StatefulProtocol;
use uuid::Uuid;

use crate::config::AppConfig;
use crate::platform::{ChannelEntry, PlatformKind};
use crate::plugin::PaneId;
use crate::recording::job::{RecordingJob, RecordingState};
use crate::recording::RecordingCommand;

/// Events generated by the daemon (serializable, cross the IPC boundary).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub enum DaemonEvent {
    ChannelsUpdated(Vec<ChannelEntry>),
    ChannelWentLive(ChannelEntry),
    ChannelWentOffline(ChannelEntry),
    StreamUrlResolved {
        channel_id: String,
        url: String,
    },
    RecordingStarted {
        job: RecordingJob,
    },
    RecordingProgress {
        job_id: Uuid,
        bytes_written: u64,
        duration_secs: f64,
    },
    RecordingFinished {
        job_id: Uuid,
        final_state: RecordingState,
        error: Option<String>,
    },
    Notification {
        title: String,
        body: String,
    },
    AllRecordingsStopped,
    DeviceCodeRequired {
        kind: PlatformKind,
        verification_uri: String,
        user_code: String,
    },
    PlatformAuthenticated {
        kind: PlatformKind,
    },
    PatreonPostFound {
        creator_name: String,
        post_title: String,
    },
    /// A cron schedule fired and a recording was kicked off. Includes the
    /// pre-generated `job_id` so the TUI can correlate with the
    /// `RecordingStarted` that follows.
    ScheduleFired {
        channel: String,
        platform: PlatformKind,
        job_id: Uuid,
        duration_secs: u64,
    },
    Error(String),
}

/// Events handled by the TUI application.
#[allow(dead_code)]
pub enum AppEvent {
    /// Events from the daemon
    Daemon(DaemonEvent),
    /// Keyboard input
    Key(crossterm::event::KeyEvent),
    /// Terminal resize
    Resize(u16, u16),
    /// Tick (frame timer)
    Tick,
    /// Thumbnail downloaded to disk
    ThumbnailReady {
        channel_id: String,
        path: PathBuf,
    },
    /// Thumbnail decoded into protocol state
    ThumbnailDecoded {
        channel_id: String,
        protocol: StatefulProtocol,
    },
    /// Watch stream URL resolved
    WatchResolved {
        channel_name: String,
        stream_url: String,
    },
    /// Watch stream URL resolution failed
    WatchFailed {
        error: String,
    },
    /// Event from a plugin's async task
    PluginEvent {
        plugin_name: &'static str,
        event: Box<dyn std::any::Any + Send>,
    },
    /// ffprobe result for a recording
    MediaProbed {
        job_id: Uuid,
        info: crate::media::MediaInfo,
    },
    /// Daemon socket dropped (client mode). Reconnect supervisor takes over.
    DaemonDisconnected,
    /// Daemon socket re-established (supervisor transparently replaces the
    /// underlying stream; the app's `daemon_tx` is still valid).
    DaemonReconnected,
    /// Forwarded from the tracing-subscriber bridge layer
    /// (`tui::log_bridge`). Lands in `event_ring` so the Shift+E pop-over
    /// can display recent tracing events alongside daemon events.
    LogBridge(UiEvent),
}

// Convenience constructors so existing code that sends DaemonEvent variants
// through AppEvent doesn't need massive refactoring everywhere at once.
impl AppEvent {
    pub fn channels_updated(channels: Vec<ChannelEntry>) -> Self {
        Self::Daemon(DaemonEvent::ChannelsUpdated(channels))
    }
    pub fn channel_went_live(channel: ChannelEntry) -> Self {
        Self::Daemon(DaemonEvent::ChannelWentLive(channel))
    }
    pub fn channel_went_offline(channel: ChannelEntry) -> Self {
        Self::Daemon(DaemonEvent::ChannelWentOffline(channel))
    }
    pub fn recording_started(job: RecordingJob) -> Self {
        Self::Daemon(DaemonEvent::RecordingStarted { job })
    }
    pub fn recording_progress(job_id: Uuid, bytes_written: u64, duration_secs: f64) -> Self {
        Self::Daemon(DaemonEvent::RecordingProgress { job_id, bytes_written, duration_secs })
    }
    pub fn recording_finished(job_id: Uuid, final_state: RecordingState, error: Option<String>) -> Self {
        Self::Daemon(DaemonEvent::RecordingFinished { job_id, final_state, error })
    }
    pub fn notification(title: String, body: String) -> Self {
        Self::Daemon(DaemonEvent::Notification { title, body })
    }
    pub fn all_recordings_stopped() -> Self {
        Self::Daemon(DaemonEvent::AllRecordingsStopped)
    }
    pub fn device_code_required(kind: PlatformKind, verification_uri: String, user_code: String) -> Self {
        Self::Daemon(DaemonEvent::DeviceCodeRequired { kind, verification_uri, user_code })
    }
    pub fn platform_authenticated(kind: PlatformKind) -> Self {
        Self::Daemon(DaemonEvent::PlatformAuthenticated { kind })
    }
    pub fn stream_url_resolved(channel_id: String, url: String) -> Self {
        Self::Daemon(DaemonEvent::StreamUrlResolved { channel_id, url })
    }
    pub fn error(msg: String) -> Self {
        Self::Daemon(DaemonEvent::Error(msg))
    }
    pub fn schedule_fired(
        channel: String,
        platform: PlatformKind,
        job_id: Uuid,
        duration_secs: u64,
    ) -> Self {
        Self::Daemon(DaemonEvent::ScheduleFired { channel, platform, job_id, duration_secs })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ActivePane {
    Sidebar,
    Detail,
    RecordingList,
    Settings,
    Log,
    Wizard,
    Schedule,
    Plugin(PaneId),
    StatusBar,
}

/// Cap for `AppState::event_ring`. Keeping the last 100 user-facing
/// events covers a typical session of clicking through the TUI without
/// blowing up memory.
pub const EVENT_RING_CAP: usize = 100;

/// Severity for a `UiEvent`. Mirrors `tracing::Level` so the live-tail
/// layer can forward without translation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UiEventLevel {
    Trace,
    Debug,
    Info,
    Warn,
    Error,
}

impl UiEventLevel {
    pub fn label(&self) -> &'static str {
        match self {
            Self::Trace => "TRACE",
            Self::Debug => "DEBUG",
            Self::Info => "INFO",
            Self::Warn => "WARN",
            Self::Error => "ERROR",
        }
    }
}

/// A single entry in the in-memory event ring buffer.
#[derive(Debug, Clone)]
pub struct UiEvent {
    pub at: chrono::DateTime<chrono::Utc>,
    pub level: UiEventLevel,
    pub source: &'static str,
    pub message: String,
}

pub struct AppState {
    pub config: AppConfig,
    pub channels: Vec<ChannelEntry>,
    pub selected_channel: usize,
    pub active_pane: ActivePane,
    pub should_quit: bool,
    pub quit_confirm: bool,
    /// Set when `StopAll` has been sent and we will force-quit if
    /// `AllRecordingsStopped` has not arrived by this deadline. Also
    /// drives the "Stopping Recordings" modal with the live countdown
    /// and per-job checklist.
    pub stop_all_deadline: Option<std::time::Instant>,
    pub status_message: String,
    /// When `status_message` was last set. Auto-dismissed from the hotkey
    /// bar roughly 5 s later so one-shot feedback doesn't become stale.
    pub status_message_at: Option<std::time::Instant>,
    pub show_help: bool,
    // Recording state
    pub recordings: HashMap<Uuid, RecordingJob>,
    pub active_recording_channels: HashSet<String>, // channel_ids with active recordings
    pub selected_recording: usize,
    /// Sticky selection by recording ID. Mirrors the Sidebar
    /// channel-id pattern so the highlight survives sort flips,
    /// finishes, deletes, and journal-replay reorderings instead of
    /// snapping to whatever index 0 happens to be after the mutation.
    pub selected_recording_id: Option<Uuid>,
    /// Multi-select set (yazi-style: insertion-ordered, dedup via parallel set).
    /// `v` toggles current row, `V` clears. Used by bulk delete (`D`) and
    /// is the foundation for future bulk rename / move.
    pub recording_selections_order: Vec<Uuid>,
    pub recording_selections_set: HashSet<Uuid>,
    /// Schedule-pane cursor.
    pub selected_schedule: usize,
    pub transcode_mode: bool,

    // Playback
    pub watching_channel: Option<String>,

    // Platform connection status
    pub twitch_connected: bool,
    pub youtube_connected: bool,
    pub patreon_connected: bool,

    // Thumbnail cache (channel_id -> protocol state for rendering)
    pub thumbnail_cache: HashMap<String, PathBuf>,
    pub thumbnail_protocols: HashMap<String, StatefulProtocol>,
    pub picker: Option<Picker>,

    // Sender for recording commands (direct mode) or daemon messages (client mode)
    pub recording_tx: Option<tokio::sync::mpsc::UnboundedSender<RecordingCommand>>,
    pub daemon_tx: Option<tokio::sync::mpsc::UnboundedSender<crate::ipc::ClientMessage>>,
    /// Standalone-mode poll-now handle. `Some` in standalone with a monitor;
    /// `None` in client mode (PollNow travels over IPC instead).
    pub poll_notify_standalone: Option<std::sync::Arc<tokio::sync::Notify>>,
    /// True while the TUI has a live daemon connection. Only meaningful in
    /// client mode; standalone mode leaves it `true` forever.
    pub daemon_connected: bool,
    /// Number of reconnect attempts since the last successful connection.
    /// Used to render the reconnect banner's "(attempt N)" counter.
    pub daemon_reconnect_attempts: u32,
    /// When the most recent disconnect was observed. Drives the banner's
    /// slide-in / fade-in animation so the transition is perceptibly smooth
    /// instead of a hard color flip.
    pub daemon_disconnected_at: Option<std::time::Instant>,

    // Settings edit state
    pub settings_selected: usize,

    // Log viewer state
    pub log_lines: Vec<String>,
    pub log_scroll: usize,
    pub log_auto_scroll: bool,
    pub log_path: PathBuf,

    // Pending device-code auth (platform, verification_uri, user_code).
    // `pending_auth` is the prompt currently shown; `auth_queue` buffers any
    // additional prompts that arrive while one is already displayed, so
    // concurrent device-code flows (Twitch + YouTube + Patreon on startup)
    // surface one after another instead of clobbering each other.
    pub pending_auth: Option<(PlatformKind, String, String)>,
    pub auth_queue: std::collections::VecDeque<(PlatformKind, String, String)>,

    // Sidebar display order: indices into app.channels in visual sort order
    pub sidebar_order: Vec<usize>,

    // Sidebar scroll offsets for autoscroll (channel index → text scroll offset)
    pub scroll_offsets: HashMap<usize, usize>,
    pub tick_counter: u64,
    /// Monotonic frame clock for time-based animations. Advanced once per
    /// render loop iteration; widgets read `dt()` / `elapsed()` for tweens
    /// and periodic pulses. See `src/tui/anim`.
    pub clock: crate::tui::anim::FrameClock,
    // Track previously selected channel for resetting scroll offset
    prev_selected_channel: usize,
    /// Shadow copy of `status_message` from the previous tick, used to
    /// detect changes and reset the auto-dismiss timer.
    prev_status_message: String,

    // Search / filter state
    pub search_active: bool,
    pub search_query: String,
    /// Char-index cursor position inside `search_query` when input is active.
    pub search_cursor: usize,
    /// Filtered sidebar indices (into app.channels). Empty = no filter active.
    pub search_filtered_channels: Vec<usize>,
    /// Filtered recording job IDs. Empty = no filter active.
    pub search_filtered_recordings: Vec<uuid::Uuid>,

    // Platform diagnostics
    /// Per-platform error ring buffer (last 10 errors each).
    pub platform_errors: HashMap<PlatformKind, Vec<String>>,
    /// Persisted set of recording UUIDs the user has played.
    /// Loaded from `{state_dir}/watched.json` on startup; written on
    /// transition to "watched" via `mark_watched()`.
    pub watched_history: HashSet<Uuid>,

    /// In-memory ring of the last `EVENT_RING_CAP` user-facing events.
    /// Feeds the Shift+E event-log pop-over (M1.3.e) and is the
    /// landing spot for the live-tracing layer (M1.3.d). Distinct from
    /// `log_lines` (raw trace tail) and `platform_errors` (per-platform).
    pub event_ring: std::collections::VecDeque<UiEvent>,
    /// Which platform debug overlay to show, if any.
    pub show_platform_debug: Option<PlatformKind>,
    /// Selected indicator index in StatusBar focus mode (among configured platforms).
    pub selected_indicator: usize,
    /// Pane to return to when leaving StatusBar focus.
    pub prev_pane: Option<ActivePane>,

    // Recording properties modal
    /// Which recording's properties modal is open.
    pub show_properties: Option<Uuid>,
    /// Cached media info from ffprobe.
    pub media_info_cache: HashMap<Uuid, crate::media::MediaInfo>,

    /// Theme picker overlay state. `Some` while the picker modal is open.
    pub theme_picker: Option<ThemePickerState>,

    /// Last observed active pane (at render time). Compared to `active_pane`
    /// to detect focus changes and restart the border-ramp animation.
    pub prev_render_pane: ActivePane,
    /// Which pane just lost focus (set at the focus-change frame, cleared
    /// once the unfocused-ramp duration has elapsed). Used by
    /// [`Self::pane_border`] to animate the leaving pane alongside the
    /// arriving one.
    pub pane_lost_focus: Option<ActivePane>,
    /// When the active pane last changed. Drives the focused-border fade-in.
    pub pane_focus_at: std::time::Instant,

    // Overlay open timestamps — `Some` iff the corresponding overlay is
    // currently on screen. Shared helper `overlay_enter()` reads these to
    // produce the entrance-animation progress for widgets.
    pub help_opened_at: Option<std::time::Instant>,
    pub quit_confirm_opened_at: Option<std::time::Instant>,
    pub properties_opened_at: Option<std::time::Instant>,
    pub platform_debug_opened_at: Option<std::time::Instant>,
    pub wizard_opened_at: Option<std::time::Instant>,
    pub stopping_opened_at: Option<std::time::Instant>,
    pub event_log_opened_at: Option<std::time::Instant>,
    /// `Some` iff the Shift+E event-log pop-over is visible.
    pub show_event_log: bool,
    /// Scroll offset within the event log (rows from top, newest-first).
    pub event_log_scroll: usize,

    /// Last hotkey pressed + when — drives the hotkey-bar shimmer.
    pub last_hotkey: Option<char>,
    pub last_hotkey_at: Option<std::time::Instant>,

    /// When each channel's thumbnail protocol last changed. Drives
    /// per-channel thumbnail crossfade in the detail pane.
    pub thumbnail_changed_at: std::collections::HashMap<String, std::time::Instant>,

    /// Number of active tweens — incremented on register, decremented on
    /// completion. When zero + no pending input, run loop widens poll to
    /// conserve CPU (adaptive frame rate — P6).
    pub active_tweens: u32,

    /// Smooth log auto-scroll target; `log_scroll` eases toward this.
    pub log_scroll_target: usize,
}

/// Which overlay to query via [`AppState::overlay_enter`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OverlayKey {
    Help,
    QuitConfirm,
    Properties,
    PlatformDebug,
    Wizard,
    Stopping,
    EventLog,
}

/// Live state for the theme picker overlay. Preview is applied immediately
/// when the cursor changes so the user sees theme switches in real time;
/// `snapshot` captures the pre-picker theme so `Esc` can undo.
pub struct ThemePickerState {
    pub themes: Vec<String>,
    pub selected: usize,
    pub snapshot: crate::tui::theme::ThemeData,
    /// When the picker opened. Drives the enter animation.
    pub opened_at: std::time::Instant,
}

fn sync_open(slot: &mut Option<std::time::Instant>, shown: bool) {
    match (shown, slot.is_some()) {
        (true, false) => *slot = Some(std::time::Instant::now()),
        (false, true) => *slot = None,
        _ => {}
    }
}

impl AppState {
    pub fn new(config: AppConfig) -> Self {
        let first_run = config.twitch.is_none() && config.youtube.is_none();
        let initial_transcode = config.recording.transcode;
        Self {
            config,
            channels: Vec::new(),
            selected_channel: 0,
            active_pane: if first_run {
                ActivePane::Wizard
            } else {
                ActivePane::Sidebar
            },
            should_quit: false,
            quit_confirm: false,
            stop_all_deadline: None,
            status_message: String::new(),
            status_message_at: None,
            show_help: false,
            recordings: HashMap::new(),
            active_recording_channels: HashSet::new(),
            selected_recording: 0,
            selected_recording_id: None,
            recording_selections_order: Vec::new(),
            recording_selections_set: HashSet::new(),
            selected_schedule: 0,
            transcode_mode: initial_transcode,
            watching_channel: None,
            twitch_connected: false,
            youtube_connected: false,
            patreon_connected: false,
            thumbnail_cache: HashMap::new(),
            thumbnail_protocols: HashMap::new(),
            picker: {
                let (tx, rx) = std::sync::mpsc::channel();
                std::thread::spawn(move || {
                    let _ = tx.send(Picker::from_query_stdio().ok());
                });
                rx.recv_timeout(std::time::Duration::from_millis(500))
                    .ok()
                    .flatten()
            },
            recording_tx: None,
            daemon_tx: None,
            poll_notify_standalone: None,
            daemon_connected: true,
            daemon_reconnect_attempts: 0,
            daemon_disconnected_at: None,
            settings_selected: 0,
            log_lines: Vec::new(),
            log_scroll: 0,
            log_auto_scroll: true,
            log_path: AppConfig::state_dir().join("strivo.log"),
            pending_auth: None,
            auth_queue: std::collections::VecDeque::new(),
            sidebar_order: Vec::new(),
            scroll_offsets: HashMap::new(),
            tick_counter: 0,
            clock: crate::tui::anim::FrameClock::new(),
            prev_selected_channel: 0,
            prev_status_message: String::new(),
            search_active: false,
            search_query: String::new(),
            search_cursor: 0,
            search_filtered_channels: Vec::new(),
            search_filtered_recordings: Vec::new(),
            platform_errors: HashMap::new(),
            watched_history: crate::recording::watch_history::load(),
            event_ring: std::collections::VecDeque::with_capacity(EVENT_RING_CAP),
            show_platform_debug: None,
            selected_indicator: 0,
            prev_pane: None,
            show_properties: None,
            media_info_cache: HashMap::new(),
            theme_picker: None,
            prev_render_pane: if first_run {
                ActivePane::Wizard
            } else {
                ActivePane::Sidebar
            },
            pane_lost_focus: None,
            pane_focus_at: std::time::Instant::now(),
            help_opened_at: None,
            quit_confirm_opened_at: None,
            properties_opened_at: None,
            platform_debug_opened_at: None,
            wizard_opened_at: if first_run { Some(std::time::Instant::now()) } else { None },
            stopping_opened_at: None,
            event_log_opened_at: None,
            show_event_log: false,
            event_log_scroll: 0,
            last_hotkey: None,
            last_hotkey_at: None,
            thumbnail_changed_at: HashMap::new(),
            active_tweens: 0,
            log_scroll_target: 0,
        }
    }

    /// Eased entrance progress in [0, 1] for the requested overlay. Returns
    /// 1.0 when the overlay isn't open or reduce-motion is active.
    pub fn overlay_enter(&self, key: OverlayKey, duration_secs: f32) -> f32 {
        let at = match key {
            OverlayKey::Help => self.help_opened_at,
            OverlayKey::QuitConfirm => self.quit_confirm_opened_at,
            OverlayKey::Properties => self.properties_opened_at,
            OverlayKey::PlatformDebug => self.platform_debug_opened_at,
            OverlayKey::Wizard => self.wizard_opened_at,
            OverlayKey::Stopping => self.stopping_opened_at,
            OverlayKey::EventLog => self.event_log_opened_at,
        };
        let Some(at) = at else {
            return 1.0;
        };
        if crate::tui::anim::reduce_motion() {
            return 1.0;
        }
        let raw = (at.elapsed().as_secs_f32() / duration_secs).clamp(0.0, 1.0);
        crate::tui::anim::easing::Ease::Standard.apply(raw)
    }

    /// Must be called once per frame before widgets render. Keeps overlay
    /// `opened_at` fields in sync with their boolean / Option flags and
    /// resets timestamps when overlays open or close.
    pub fn update_overlay_timing(&mut self) {
        sync_open(&mut self.help_opened_at, self.show_help);
        sync_open(&mut self.quit_confirm_opened_at, self.quit_confirm);
        sync_open(&mut self.properties_opened_at, self.show_properties.is_some());
        sync_open(
            &mut self.platform_debug_opened_at,
            self.show_platform_debug.is_some(),
        );
        let wizard_live =
            self.active_pane == ActivePane::Wizard || self.pending_auth.is_some();
        sync_open(&mut self.wizard_opened_at, wizard_live);
        sync_open(&mut self.stopping_opened_at, self.stop_all_deadline.is_some());
        sync_open(&mut self.event_log_opened_at, self.show_event_log);
    }

    /// Seconds since the active pane last changed. Used by widget borders to
    /// ramp in a cyan glow on focus (see `Theme::border_focused_ramp`).
    pub fn focus_fade_secs(&self) -> f32 {
        self.pane_focus_at.elapsed().as_secs_f32()
    }

    /// Must be called once per frame before widgets render so pane-focus
    /// transitions get a fresh start timestamp when the active pane changes.
    pub fn update_focus_timing(&mut self) {
        if self.prev_render_pane != self.active_pane {
            self.pane_lost_focus = Some(self.prev_render_pane.clone());
            self.pane_focus_at = std::time::Instant::now();
            self.prev_render_pane = self.active_pane.clone();
        } else if self
            .pane_lost_focus
            .is_some()
            && self.pane_focus_at.elapsed().as_secs_f32() > 0.14
        {
            // Unfocused ramp has settled — stop drawing it.
            self.pane_lost_focus = None;
        }
    }

    /// Returns `true` when at least one animation is live, so the TUI run
    /// loop should stay at the 16 ms fast cadence. When everything is quiet
    /// it drops to a slower poll (see `poll_duration`) to conserve CPU.
    pub fn needs_fast_frame(&self) -> bool {
        // Always-on surfaces with periodic motion.
        if self.theme_picker.is_some() {
            return true;
        }
        if self.search_active {
            return true;
        }
        if self.active_recording_count() > 0 {
            return true;
        }
        // Anything resolving or stopping is animated.
        let has_transient_state = self.recordings.values().any(|r| {
            matches!(
                r.state,
                crate::recording::job::RecordingState::ResolvingUrl
                    | crate::recording::job::RecordingState::Stopping
                    | crate::recording::job::RecordingState::Failed
            )
        });
        if has_transient_state {
            return true;
        }
        // Any live channel pulses the LIVE badge in channel_detail.
        if self.channels.iter().any(|c| c.is_live) {
            return true;
        }
        // Transient bounded animations — check whether their timer is still
        // within the active window (with slack to cover the tail).
        let within =
            |at: Option<std::time::Instant>, limit_secs: f32| -> bool {
                at.map(|t| t.elapsed().as_secs_f32() < limit_secs)
                    .unwrap_or(false)
            };
        if within(self.last_hotkey_at, 0.28) {
            return true;
        }
        if within(Some(self.pane_focus_at), 0.22) {
            return true;
        }
        if within(self.help_opened_at, 0.22)
            || within(self.quit_confirm_opened_at, 0.22)
            || within(self.properties_opened_at, 0.22)
            || within(self.platform_debug_opened_at, 0.22)
            || within(self.wizard_opened_at, 0.28)
            || within(self.stopping_opened_at, 0.22)
        {
            return true;
        }
        if within(self.daemon_disconnected_at, 0.24) {
            return true;
        }
        if self
            .thumbnail_changed_at
            .values()
            .any(|t| t.elapsed().as_secs_f32() < 0.65)
        {
            return true;
        }
        if self
            .status_message_at
            .map(|t| t.elapsed().as_secs_f32() > 4.3 && t.elapsed().as_secs_f32() < 5.2)
            .unwrap_or(false)
        {
            // Toast fade window.
            return true;
        }
        false
    }

    /// Frame duration to use for this frame. 16 ms when something is
    /// animating, 120 ms when the UI is quiescent.
    pub fn poll_duration(&self) -> std::time::Duration {
        if crate::tui::anim::reduce_motion() {
            return std::time::Duration::from_millis(120);
        }
        if self.needs_fast_frame() {
            std::time::Duration::from_millis(16)
        } else {
            std::time::Duration::from_millis(120)
        }
    }

    /// Border style for a pane, picking the right focus animation.
    ///
    /// - Currently active pane → dim → primary fade-in (180 ms).
    /// - Pane that just lost focus → primary → dim fade-out (120 ms).
    /// - Otherwise → static dim.
    pub fn pane_border(&self, this: &ActivePane) -> ratatui::style::Style {
        use crate::tui::theme::Theme;
        if self.active_pane == *this {
            Theme::border_focused_ramp(self.focus_fade_secs())
        } else if self.pane_lost_focus.as_ref() == Some(this)
            && self.focus_fade_secs() < 0.14
        {
            Theme::border_unfocused_ramp(self.focus_fade_secs())
        } else {
            Theme::border()
        }
    }

    /// Send a recording command through the appropriate channel (direct or daemon).
    pub fn send_recording_command(&self, cmd: RecordingCommand) {
        if let Some(ref tx) = self.daemon_tx {
            let _ = tx.send(crate::ipc::ClientMessage::Recording(cmd));
        } else if let Some(ref tx) = self.recording_tx {
            let _ = tx.send(cmd);
        }
    }

    /// Request an immediate channel re-poll. Wired to F5. In daemon mode
    /// this travels over IPC; in standalone mode we notify the monitor's
    /// poll_notify handle directly.
    pub fn request_poll_now(&mut self) {
        if let Some(ref tx) = self.daemon_tx {
            match tx.send(crate::ipc::ClientMessage::PollNow) {
                Ok(()) => {
                    self.status_message = "Refreshing channels…".to_string();
                }
                Err(_) => {
                    self.status_message = "Refresh failed — daemon connection closed".to_string();
                }
            }
        } else if let Some(ref notify) = self.poll_notify_standalone {
            notify.notify_one();
            self.status_message = "Refreshing channels…".to_string();
        } else {
            self.status_message = "Refresh unavailable — no platforms authenticated".to_string();
        }
    }

    pub fn active_recording_count(&self) -> usize {
        self.recordings
            .values()
            .filter(|r| {
                r.state == RecordingState::Recording || r.state == RecordingState::ResolvingUrl
            })
            .count()
    }

    pub fn sorted_recordings(&self) -> Vec<&RecordingJob> {
        let mut recs: Vec<&RecordingJob> = self.recordings.values().collect();
        recs.sort_by(|a, b| b.started_at.cmp(&a.started_at));
        recs
    }

    /// Re-derive `selected_recording` from `selected_recording_id` after
    /// any mutation to `recordings`. If the tracked ID is gone (deletion,
    /// cleanup), the selection falls back to index 0 and the tracked ID
    /// is updated to whatever sits there. Call after any insert/remove.
    pub fn reconcile_selected_recording(&mut self) {
        let ids: Vec<Uuid> = self.sorted_recordings().iter().map(|r| r.id).collect();
        if ids.is_empty() {
            self.selected_recording = 0;
            self.selected_recording_id = None;
            return;
        }
        if let Some(id) = self.selected_recording_id {
            if let Some(idx) = ids.iter().position(|&i| i == id) {
                self.selected_recording = idx;
                return;
            }
        }
        // ID is gone (or never tracked) — clamp to the current top.
        let clamped = self.selected_recording.min(ids.len() - 1);
        self.selected_recording = clamped;
        self.selected_recording_id = ids.get(clamped).copied();
    }

    /// Update `selected_recording_id` to match the current index. Call
    /// from key handlers that move the cursor.
    pub fn remember_recording_selection(&mut self) {
        let ids: Vec<Uuid> = self.sorted_recordings().iter().map(|r| r.id).collect();
        self.selected_recording_id = ids.get(self.selected_recording).copied();
    }

    /// Groups finished+active recordings by day label ("Today", "Yesterday", "March 12, 2026"), newest first
    pub fn recordings_by_day(&self) -> Vec<(String, Vec<&RecordingJob>)> {
        use chrono::Local;

        let mut recs = self.sorted_recordings();
        // sorted_recordings already sorts newest first
        if recs.is_empty() {
            return Vec::new();
        }

        let today = Local::now().date_naive();
        let yesterday = today - chrono::Duration::days(1);

        let mut groups: Vec<(String, Vec<&RecordingJob>)> = Vec::new();

        for rec in recs.drain(..) {
            let rec_date = rec.started_at.with_timezone(&Local).date_naive();
            let label = if rec_date == today {
                "Today".to_string()
            } else if rec_date == yesterday {
                "Yesterday".to_string()
            } else {
                rec_date.format("%B %-d, %Y").to_string()
            };

            if let Some(last) = groups.last_mut() {
                if last.0 == label {
                    last.1.push(rec);
                    continue;
                }
            }
            groups.push((label, vec![rec]));
        }

        groups
    }

    /// Counts finished recordings where `watched == false` for a given channel
    pub fn unwatched_count_for_channel(&self, channel_id: &str) -> usize {
        self.recordings
            .values()
            .filter(|r| {
                r.channel_id == channel_id
                    && r.state == RecordingState::Finished
                    && !r.watched
            })
            .count()
    }

    pub fn handle_event(&mut self, event: AppEvent) -> Option<AppAction> {
        match event {
            AppEvent::Key(key) => return self.handle_key(key),
            AppEvent::Resize(_, _) => {}
            AppEvent::Tick => {
                self.tick_counter = self.tick_counter.wrapping_add(1);
                // Reset scroll offset when selection changes
                if self.selected_channel != self.prev_selected_channel {
                    self.scroll_offsets.remove(&self.prev_selected_channel);
                    self.prev_selected_channel = self.selected_channel;
                }
                // Status message auto-dismiss (≈5 s after the last change)
                if self.status_message != self.prev_status_message {
                    self.prev_status_message = self.status_message.clone();
                    self.status_message_at = if self.status_message.is_empty() {
                        None
                    } else {
                        Some(std::time::Instant::now())
                    };
                } else if let Some(at) = self.status_message_at {
                    if at.elapsed().as_secs() >= 5 {
                        self.status_message.clear();
                        self.status_message_at = None;
                        self.prev_status_message.clear();
                    }
                }
                // Autoscroll stream title for selected live channel in sidebar
                if self.active_pane == ActivePane::Sidebar {
                    if let Some(ch) = self.channels.get(self.selected_channel) {
                        if ch.is_live && ch.stream_title.is_some() {
                            if self.tick_counter % 6 == 0 {
                                let offset = self.scroll_offsets.entry(self.selected_channel).or_insert(0);
                                *offset += 1;
                            }
                        }
                    }
                }
            }
            AppEvent::ThumbnailReady { channel_id, path } => {
                self.thumbnail_cache.insert(channel_id.clone(), path);
            }
            AppEvent::ThumbnailDecoded { channel_id, protocol } => {
                self.thumbnail_changed_at
                    .insert(channel_id.clone(), std::time::Instant::now());
                self.thumbnail_protocols.insert(channel_id, protocol);
            }
            AppEvent::WatchResolved { channel_name, stream_url } => {
                self.watching_channel = Some(channel_name.clone());
                return Some(AppAction::LaunchMpv {
                    channel_name,
                    url: stream_url,
                });
            }
            AppEvent::WatchFailed { error } => {
                self.status_message = format!("Watch failed: {error}");
            }
            AppEvent::Daemon(de) => return self.handle_daemon_event(de),
            // PluginEvent is handled by the caller (tui::run_loop) which owns the registry
            AppEvent::PluginEvent { .. } => {}
            AppEvent::MediaProbed { job_id, info } => {
                self.media_info_cache.insert(job_id, info);
            }
            AppEvent::DaemonDisconnected => {
                if self.daemon_connected {
                    self.daemon_disconnected_at = Some(std::time::Instant::now());
                }
                self.daemon_connected = false;
                self.daemon_reconnect_attempts = self.daemon_reconnect_attempts.saturating_add(1);
                self.status_message = "⚠ Daemon disconnected — reconnecting…".to_string();
            }
            AppEvent::DaemonReconnected => {
                self.daemon_connected = true;
                self.daemon_reconnect_attempts = 0;
                self.daemon_disconnected_at = None;
                self.status_message = "✓ Daemon reconnected".to_string();
            }
            AppEvent::LogBridge(ev) => {
                if self.event_ring.len() >= EVENT_RING_CAP {
                    self.event_ring.pop_front();
                }
                self.event_ring.push_back(ev);
            }
        }
        None
    }

    /// Push a user-facing event onto the in-memory ring. Sized to
    /// EVENT_RING_CAP; oldest entries fall off the front.
    pub fn push_event(
        &mut self,
        level: UiEventLevel,
        source: &'static str,
        message: impl Into<String>,
    ) {
        if self.event_ring.len() >= EVENT_RING_CAP {
            self.event_ring.pop_front();
        }
        self.event_ring.push_back(UiEvent {
            at: chrono::Utc::now(),
            level,
            source,
            message: message.into(),
        });
    }

    pub fn handle_daemon_event(&mut self, event: DaemonEvent) -> Option<AppAction> {
        // Mirror the event into the user-facing ring before dispatch so
        // every variant lands there even when the handler is a no-op.
        let (level, message): (UiEventLevel, String) = match &event {
            DaemonEvent::ChannelWentLive(ch) => (
                UiEventLevel::Info,
                format!("{} went live", ch.display_name),
            ),
            DaemonEvent::ChannelWentOffline(ch) => (
                UiEventLevel::Info,
                format!("{} went offline", ch.display_name),
            ),
            DaemonEvent::RecordingStarted { job } => (
                UiEventLevel::Info,
                format!("Recording started: {}", job.channel_name),
            ),
            DaemonEvent::RecordingFinished { job_id, final_state, error } => {
                let level = match final_state {
                    RecordingState::Finished => UiEventLevel::Info,
                    RecordingState::Failed => UiEventLevel::Warn,
                    _ => UiEventLevel::Info,
                };
                let msg = if let Some(e) = error {
                    format!("Recording {job_id} → {final_state}: {e}")
                } else {
                    format!("Recording {job_id} → {final_state}")
                };
                (level, msg)
            }
            DaemonEvent::ScheduleFired { channel, duration_secs, .. } => (
                UiEventLevel::Info,
                format!("Schedule fired: {channel} ({} min)", duration_secs / 60),
            ),
            DaemonEvent::PlatformAuthenticated { kind } => {
                (UiEventLevel::Info, format!("{kind} connected"))
            }
            DaemonEvent::Notification { title, body } => (
                UiEventLevel::Info,
                if body.is_empty() { title.clone() } else { format!("{title}: {body}") },
            ),
            DaemonEvent::Error(msg) => (UiEventLevel::Error, msg.clone()),
            _ => (UiEventLevel::Trace, String::new()),
        };
        if !message.is_empty() {
            self.push_event(level, "daemon", message);
        }

        match event {
            DaemonEvent::ChannelsUpdated(channels) => {
                // Remember currently selected channel by ID
                let prev_selected_id = self.channels.get(self.selected_channel).map(|ch| ch.id.clone());

                // Preserve auto_record settings from config
                let mut updated = channels;
                for ch in &mut updated {
                    ch.auto_record = self.config.auto_record_channels.iter().any(|a| {
                        a.channel_id == ch.id && a.platform == ch.platform.to_string()
                    });
                }
                self.channels = updated;

                // Restore selection by ID, fall back to clamping
                if let Some(ref prev_id) = prev_selected_id {
                    if let Some(new_idx) = self.channels.iter().position(|ch| &ch.id == prev_id) {
                        self.selected_channel = new_idx;
                    } else if self.selected_channel >= self.channels.len() {
                        self.selected_channel = self.channels.len().saturating_sub(1);
                    }
                } else if self.selected_channel >= self.channels.len() {
                    self.selected_channel = self.channels.len().saturating_sub(1);
                }

                // Prune stale thumbnail entries
                let current_ids: HashSet<String> = self.channels.iter().map(|ch| ch.id.clone()).collect();
                self.thumbnail_cache.retain(|id, _| current_ids.contains(id));
                self.thumbnail_protocols.retain(|id, _| current_ids.contains(id));

                self.rebuild_sidebar_order();
            }
            DaemonEvent::ChannelWentLive(ref channel) => {
                self.status_message = format!("{} went live!", channel.display_name);
                return Some(AppAction::Notify {
                    title: format!("{} is live!", channel.display_name),
                    body: channel
                        .stream_title
                        .clone()
                        .unwrap_or_else(|| "Stream started".to_string()),
                });
            }
            DaemonEvent::ChannelWentOffline(channel) => {
                self.status_message = format!("{} went offline", channel.display_name);
            }
            DaemonEvent::StreamUrlResolved { channel_id, .. } => {
                self.status_message = format!("Stream URL resolved for {channel_id}");
            }
            DaemonEvent::RecordingStarted { mut job } => {
                if self.watched_history.contains(&job.id) {
                    job.watched = true;
                }
                self.status_message = format!("Recording started: {}", job.channel_name);
                self.recordings.insert(job.id, job);
                self.rebuild_active_channels();
                self.rebuild_sidebar_order();
                self.reconcile_selected_recording();
            }
            DaemonEvent::RecordingProgress {
                job_id,
                bytes_written,
                duration_secs,
            } => {
                if let Some(job) = self.recordings.get_mut(&job_id) {
                    job.bytes_written = bytes_written;
                    job.duration_secs = duration_secs;
                    job.state = RecordingState::Recording;
                }
            }
            DaemonEvent::RecordingFinished { job_id, final_state, error } => {
                if let Some(job) = self.recordings.get_mut(&job_id) {
                    job.state = final_state;
                    job.error = error;
                }
                self.rebuild_active_channels();
                self.rebuild_sidebar_order();
                // Selection list is sorted by started_at so finishes don't
                // reorder, but recording UUIDs that get removed elsewhere
                // (e.g. future M1.3.b delete-to-trash) would; keep the
                // index in sync regardless.
                self.reconcile_selected_recording();
                let active = self.active_recording_count();
                self.status_message = format!("Recording finished ({active} active)");
            }
            DaemonEvent::Notification { title, body } => {
                return Some(AppAction::Notify { title, body });
            }
            DaemonEvent::AllRecordingsStopped => {
                self.should_quit = true;
            }
            DaemonEvent::DeviceCodeRequired { kind, verification_uri, user_code } => {
                self.status_message = format!(
                    "{kind} auth: go to {verification_uri} and enter code: {user_code}"
                );
                let entry = (kind, verification_uri, user_code);
                // Deduplicate: a re-fire for the same platform replaces the
                // previous code rather than stacking.
                if matches!(&self.pending_auth, Some((p, _, _)) if *p == entry.0) {
                    self.pending_auth = Some(entry);
                } else {
                    self.auth_queue.retain(|(p, _, _)| *p != entry.0);
                    if self.pending_auth.is_none() {
                        self.pending_auth = Some(entry);
                    } else {
                        self.auth_queue.push_back(entry);
                    }
                }
            }
            DaemonEvent::PlatformAuthenticated { kind } => {
                match kind {
                    PlatformKind::Twitch => self.twitch_connected = true,
                    PlatformKind::YouTube => self.youtube_connected = true,
                    PlatformKind::Patreon => self.patreon_connected = true,
                }
                self.status_message = format!("{kind} connected");
                if matches!(&self.pending_auth, Some((pending, _, _)) if *pending == kind) {
                    self.pending_auth = self.auth_queue.pop_front();
                }
                self.auth_queue.retain(|(p, _, _)| *p != kind);
            }
            DaemonEvent::PatreonPostFound { creator_name, post_title } => {
                self.status_message = format!("Patreon: {creator_name} posted '{post_title}'");
            }
            DaemonEvent::ScheduleFired { channel, duration_secs, .. } => {
                let mins = duration_secs / 60;
                self.status_message =
                    format!("Schedule fired: {channel} ({mins} min)");
            }
            DaemonEvent::Error(ref msg) => {
                self.status_message = format!("Error: {msg}");
                // Categorize error by platform keywords for the diagnostics view
                let msg_lower = msg.to_lowercase();
                let kind = if msg_lower.contains("twitch") || msg_lower.contains("streamlink") {
                    Some(PlatformKind::Twitch)
                } else if msg_lower.contains("youtube") || msg_lower.contains("yt-dlp") || msg_lower.contains("ytdlp") {
                    Some(PlatformKind::YouTube)
                } else if msg_lower.contains("patreon") {
                    Some(PlatformKind::Patreon)
                } else {
                    None
                };
                if let Some(kind) = kind {
                    let errors = self.platform_errors.entry(kind).or_default();
                    errors.push(msg.clone());
                    if errors.len() > 10 {
                        errors.remove(0);
                    }
                }
            }
        }
        None
    }

    fn handle_key(&mut self, key: crossterm::event::KeyEvent) -> Option<AppAction> {
        use crossterm::event::{KeyCode, KeyEventKind};

        if key.kind != KeyEventKind::Press {
            return None;
        }

        // C5.2 — remember the last character keypress so the status-bar
        // hotkey it corresponds to can shimmer briefly.
        if let KeyCode::Char(c) = key.code {
            self.last_hotkey = Some(c);
            self.last_hotkey_at = Some(std::time::Instant::now());
        }

        // Search mode input handling — intercept all keys
        if self.search_active {
            match key.code {
                KeyCode::Esc => {
                    self.clear_search();
                }
                KeyCode::Enter => {
                    // Confirm filter and exit search input mode (filter stays active)
                    self.search_active = false;
                    if self.search_query.is_empty() {
                        self.clear_search();
                    }
                }
                KeyCode::Backspace => {
                    if self.search_cursor > 0 {
                        let chars: Vec<char> = self.search_query.chars().collect();
                        let new_cursor = self.search_cursor - 1;
                        self.search_query = chars
                            .iter()
                            .enumerate()
                            .filter(|(i, _)| *i != new_cursor)
                            .map(|(_, c)| *c)
                            .collect();
                        self.search_cursor = new_cursor;
                        self.update_search_filter();
                    }
                }
                KeyCode::Delete => {
                    let chars: Vec<char> = self.search_query.chars().collect();
                    if self.search_cursor < chars.len() {
                        self.search_query = chars
                            .iter()
                            .enumerate()
                            .filter(|(i, _)| *i != self.search_cursor)
                            .map(|(_, c)| *c)
                            .collect();
                        self.update_search_filter();
                    }
                }
                KeyCode::Left => {
                    self.search_cursor = self.search_cursor.saturating_sub(1);
                }
                KeyCode::Right => {
                    let len = self.search_query.chars().count();
                    if self.search_cursor < len {
                        self.search_cursor += 1;
                    }
                }
                KeyCode::Home => {
                    self.search_cursor = 0;
                }
                KeyCode::End => {
                    self.search_cursor = self.search_query.chars().count();
                }
                KeyCode::Char(c) => {
                    let mut chars: Vec<char> = self.search_query.chars().collect();
                    chars.insert(self.search_cursor, c);
                    self.search_query = chars.iter().collect();
                    self.search_cursor += 1;
                    self.update_search_filter();
                }
                _ => {}
            }
            return None;
        }

        // Wizard overlay owns `o` while a device-code flow is live, even if
        // the user is on another pane. Everything else falls through so the
        // underlying pane keeps behaving normally.
        if self.pending_auth.is_some() && self.active_pane != ActivePane::Wizard {
            if let KeyCode::Char('o') | KeyCode::Char('O') = key.code {
                if let Some((_, ref uri, _)) = self.pending_auth {
                    let url = uri.clone();
                    self.status_message = format!("Opening {url}…");
                    return Some(AppAction::OpenUrl { url });
                }
            }
        }

        // Quit confirmation handling
        if self.quit_confirm {
            match key.code {
                KeyCode::Char('y') | KeyCode::Char('Y') => {
                    // Stop all recordings — quit will happen when AllRecordingsStopped arrives
                    self.send_recording_command(RecordingCommand::StopAll);
                    self.status_message = "Stopping recordings...".to_string();
                    self.quit_confirm = false;
                    return None;
                }
                KeyCode::Char('n') | KeyCode::Char('N') | KeyCode::Esc => {
                    self.quit_confirm = false;
                    self.status_message.clear();
                    return None;
                }
                _ => return None,
            }
        }

        // Theme picker overlay — swallows all keys while open.
        if self.theme_picker.is_some() {
            self.handle_theme_picker_key(key);
            return None;
        }

        // Modal overlay dismiss (before global/pane keys)
        if self.show_platform_debug.is_some() {
            if matches!(key.code, KeyCode::Esc | KeyCode::Enter) {
                self.show_platform_debug = None;
            }
            return None;
        }

        if self.show_properties.is_some() {
            if matches!(key.code, KeyCode::Esc | KeyCode::Char('i')) {
                self.show_properties = None;
            }
            return None;
        }

        // Global keys
        match key.code {
            // Ctrl+D: enter StatusBar diagnostic focus
            KeyCode::Char('d') if key.modifiers.contains(crossterm::event::KeyModifiers::CONTROL) => {
                if self.active_pane != ActivePane::StatusBar {
                    self.prev_pane = Some(self.active_pane.clone());
                    self.active_pane = ActivePane::StatusBar;
                    self.selected_indicator = 0;
                }
                return None;
            }
            KeyCode::Char('q') if self.active_pane != ActivePane::Wizard => {
                if self.active_recording_count() > 0 {
                    self.quit_confirm = true;
                    self.status_message =
                        "Recordings active! Quit? (y/n)".to_string();
                } else {
                    self.should_quit = true;
                }
                return None;
            }
            KeyCode::Char('?') => {
                self.show_help = !self.show_help;
                return None;
            }
            // Ctrl+T: open theme picker overlay
            KeyCode::Char('t') if key.modifiers.contains(crossterm::event::KeyModifiers::CONTROL) => {
                self.open_theme_picker();
                return None;
            }
            KeyCode::Esc if self.show_help => {
                self.show_help = false;
                return None;
            }
            // Shift+E: toggle event-log pop-over.
            KeyCode::Char('E')
                if key.modifiers.contains(crossterm::event::KeyModifiers::SHIFT) =>
            {
                self.show_event_log = !self.show_event_log;
                self.event_log_scroll = 0;
                return None;
            }
            _ if self.show_event_log => {
                // Captures j/k/g/G/Esc while the overlay is up.
                match key.code {
                    KeyCode::Esc => self.show_event_log = false,
                    KeyCode::Char('j') | KeyCode::Down => {
                        let max = self.event_ring.len().saturating_sub(1);
                        if self.event_log_scroll < max {
                            self.event_log_scroll += 1;
                        }
                    }
                    KeyCode::Char('k') | KeyCode::Up => {
                        if self.event_log_scroll > 0 {
                            self.event_log_scroll -= 1;
                        }
                    }
                    KeyCode::Char('g') | KeyCode::Home => {
                        self.event_log_scroll = 0;
                    }
                    KeyCode::Char('G') | KeyCode::End => {
                        self.event_log_scroll =
                            self.event_ring.len().saturating_sub(1);
                    }
                    _ => {}
                }
                return None;
            }
            KeyCode::Char('F')
                if self.active_pane != ActivePane::Wizard
                    && self.active_pane != ActivePane::Log =>
            {
                self.clear_search();
                self.refresh_log();
                self.active_pane = ActivePane::Log;
                return None;
            }
            KeyCode::Char('S')
                if self.active_pane != ActivePane::Wizard
                    && self.active_pane != ActivePane::Schedule =>
            {
                self.clear_search();
                self.active_pane = ActivePane::Schedule;
                self.selected_schedule = self
                    .selected_schedule
                    .min(self.config.schedule.len().saturating_sub(1));
                return None;
            }
            KeyCode::Char('/') if matches!(self.active_pane, ActivePane::Sidebar | ActivePane::RecordingList | ActivePane::Detail) => {
                self.search_active = true;
                self.search_query.clear();
                self.search_cursor = 0;
                self.search_filtered_channels.clear();
                self.search_filtered_recordings.clear();
                return None;
            }
            // Plugin activation commands are handled by the caller which owns the registry.
            // Return None here; the TUI event loop checks pane_for_command separately.
            _ => {}
        }

        match self.active_pane {
            ActivePane::Sidebar => self.handle_sidebar_key(key),
            ActivePane::Detail => self.handle_detail_key(key),
            ActivePane::RecordingList => self.handle_recording_list_key(key),
            ActivePane::Settings => self.handle_settings_key(key),
            ActivePane::Log => self.handle_log_key(key),
            ActivePane::Wizard => self.handle_wizard_key(key),
            ActivePane::Schedule => self.handle_schedule_key(key),
            // Plugin key events handled by caller which owns the registry
            ActivePane::Plugin(_) => None,
            ActivePane::StatusBar => self.handle_status_bar_key(key),
        }
    }

    /// Schedule pane: j/k navigate, D delete current row (writes config),
    /// Esc/h returns to Sidebar. Add/edit modals are deferred until the
    /// generic text-input modal lands (alongside rename/move in M1.3.b).
    fn handle_schedule_key(
        &mut self,
        key: crossterm::event::KeyEvent,
    ) -> Option<AppAction> {
        use crossterm::event::KeyCode;
        let count = self.config.schedule.len();
        if count > 0 {
            self.selected_schedule = self.selected_schedule.min(count - 1);
        }
        match key.code {
            KeyCode::Esc | KeyCode::Char('h') | KeyCode::Left => {
                self.active_pane = ActivePane::Sidebar;
            }
            KeyCode::Char('j') | KeyCode::Down if count > 0 => {
                self.selected_schedule = (self.selected_schedule + 1) % count;
            }
            KeyCode::Char('k') | KeyCode::Up if count > 0 => {
                self.selected_schedule = if self.selected_schedule == 0 {
                    count - 1
                } else {
                    self.selected_schedule - 1
                };
            }
            KeyCode::Char('g') | KeyCode::Home if count > 0 => {
                self.selected_schedule = 0;
            }
            KeyCode::Char('G') | KeyCode::End if count > 0 => {
                self.selected_schedule = count - 1;
            }
            KeyCode::Char('D') if count > 0 => {
                let removed = self.config.schedule.remove(self.selected_schedule);
                if let Err(e) = self.config.save(None) {
                    self.status_message =
                        format!("Schedule removed in-memory but save failed: {e}");
                } else {
                    self.status_message = format!(
                        "Removed schedule for {} ({})",
                        removed.channel, removed.cron
                    );
                }
                let new_count = self.config.schedule.len();
                if new_count == 0 {
                    self.selected_schedule = 0;
                } else if self.selected_schedule >= new_count {
                    self.selected_schedule = new_count - 1;
                }
            }
            _ => {}
        }
        None
    }

    /// Open the theme picker, snapshot current theme so Esc can revert.
    pub fn open_theme_picker(&mut self) {
        let themes = crate::tui::theme::available_themes();
        if themes.is_empty() {
            self.status_message = "No themes found".to_string();
            return;
        }
        let current = crate::tui::theme::Theme::current_name();
        let selected = themes.iter().position(|t| *t == current).unwrap_or(0);
        self.theme_picker = Some(ThemePickerState {
            themes,
            selected,
            snapshot: crate::tui::theme::Theme::snapshot(),
            opened_at: std::time::Instant::now(),
        });
    }

    /// Apply the currently-selected picker theme as a transient preview.
    fn preview_picker_selection(&self) {
        let Some(ref state) = self.theme_picker else {
            return;
        };
        let Some(name) = state.themes.get(state.selected) else {
            return;
        };
        crate::tui::theme::Theme::set_with_overrides(
            name,
            self.config.theme.colors(),
            self.config.theme.ansi(),
        );
    }

    fn handle_theme_picker_key(&mut self, key: crossterm::event::KeyEvent) {
        use crossterm::event::KeyCode;
        let Some(state) = self.theme_picker.as_mut() else {
            return;
        };
        match key.code {
            KeyCode::Down | KeyCode::Char('j') => {
                if !state.themes.is_empty() {
                    state.selected = (state.selected + 1) % state.themes.len();
                }
                self.preview_picker_selection();
            }
            KeyCode::Up | KeyCode::Char('k') => {
                if !state.themes.is_empty() {
                    state.selected = if state.selected == 0 {
                        state.themes.len() - 1
                    } else {
                        state.selected - 1
                    };
                }
                self.preview_picker_selection();
            }
            KeyCode::Home | KeyCode::Char('g') => {
                state.selected = 0;
                self.preview_picker_selection();
            }
            KeyCode::End | KeyCode::Char('G') => {
                state.selected = state.themes.len().saturating_sub(1);
                self.preview_picker_selection();
            }
            KeyCode::Char('r') | KeyCode::Char('R') => {
                let current_name = state
                    .themes
                    .get(state.selected)
                    .cloned()
                    .unwrap_or_default();
                let rescanned = crate::tui::theme::available_themes();
                let new_selected = rescanned
                    .iter()
                    .position(|t| *t == current_name)
                    .unwrap_or(0);
                state.themes = rescanned;
                state.selected = new_selected;
                self.preview_picker_selection();
                self.status_message = "Themes rescanned".to_string();
            }
            KeyCode::Enter => {
                let picked = state
                    .themes
                    .get(state.selected)
                    .cloned()
                    .unwrap_or_default();
                self.theme_picker = None;
                if !picked.is_empty() {
                    self.config.theme.set_name(picked.clone());
                    if let Err(e) = self.config.save(None) {
                        tracing::warn!("theme picker: save failed: {e}");
                        self.status_message = format!("Theme save failed: {e}");
                    } else {
                        self.status_message = format!("Theme: {picked}");
                    }
                }
            }
            KeyCode::Esc => {
                let snap = state.snapshot.clone();
                self.theme_picker = None;
                crate::tui::theme::Theme::restore(snap);
            }
            _ => {}
        }
    }

    fn handle_wizard_key(&mut self, key: crossterm::event::KeyEvent) -> Option<AppAction> {
        use crossterm::event::KeyCode;
        match key.code {
            KeyCode::Char('o') | KeyCode::Char('O') => {
                // Open the current device-code verification URL in the
                // default browser. When nothing is pending we fall through.
                if let Some((_, ref uri, _)) = self.pending_auth {
                    let url = uri.clone();
                    self.status_message = format!("Opening {url}…");
                    return Some(AppAction::OpenUrl { url });
                }
            }
            KeyCode::Char('q') => {
                self.should_quit = true;
            }
            KeyCode::Esc => {
                // Users who want to inspect the TUI without credentials.
                self.active_pane = ActivePane::Sidebar;
                if self.channels.is_empty() {
                    self.status_message =
                        "No channels configured \u{2014} press S for Settings".to_string();
                }
            }
            _ => {}
        }
        None
    }

    fn handle_sidebar_key(&mut self, key: crossterm::event::KeyEvent) -> Option<AppAction> {
        use crossterm::event::KeyCode;

        match key.code {
            KeyCode::Esc if !self.search_query.is_empty() => {
                self.clear_search();
            }
            KeyCode::Char('j') | KeyCode::Down => {
                self.navigate_channel(true);
            }
            KeyCode::Char('k') | KeyCode::Up => {
                self.navigate_channel(false);
            }
            KeyCode::Char('g') | KeyCode::Home => {
                self.jump_channel_to(true);
            }
            KeyCode::Char('G') | KeyCode::End => {
                self.jump_channel_to(false);
            }
            KeyCode::Enter | KeyCode::Right | KeyCode::Char('l') => {
                if !self.channels.is_empty() {
                    self.active_pane = ActivePane::Detail;
                }
            }
            KeyCode::Char('L') => {
                self.active_pane = ActivePane::RecordingList;
            }
            KeyCode::Char('s') | KeyCode::Char('C') => {
                self.active_pane = ActivePane::Settings;
            }
            _ => {}
        }
        None
    }

    fn handle_detail_key(
        &mut self,
        key: crossterm::event::KeyEvent,
    ) -> Option<AppAction> {
        use crossterm::event::KeyCode;

        match key.code {
            KeyCode::Esc if !self.search_query.is_empty() => {
                self.clear_search();
            }
            KeyCode::Esc | KeyCode::Char('h') | KeyCode::Left => {
                self.active_pane = ActivePane::Sidebar;
            }
            KeyCode::Char('j') | KeyCode::Down => {
                self.navigate_channel(true);
            }
            KeyCode::Char('k') | KeyCode::Up => {
                self.navigate_channel(false);
            }
            KeyCode::Char('g') | KeyCode::Home => {
                self.jump_channel_to(true);
            }
            KeyCode::Char('G') | KeyCode::End => {
                self.jump_channel_to(false);
            }
            KeyCode::Char('r') => {
                // Start recording
                if let Some(ch) = self.selected_channel() {
                    if !ch.is_live {
                        self.status_message = "Channel is not live".to_string();
                        return None;
                    }
                    if self.is_channel_recording(&ch.id) {
                        self.status_message = format!("Already recording {}", ch.display_name);
                        return None;
                    }
                    let ch = ch.clone();
                    return Some(AppAction::StartRecording {
                        channel_id: ch.id,
                        channel_name: ch.name,
                        platform: ch.platform,
                        transcode: self.transcode_mode,
                        from_start: false,
                    });
                }
            }
            KeyCode::Char('R') => {
                // Record from start (YouTube only — uses yt-dlp --live-from-start)
                if let Some(ch) = self.selected_channel() {
                    if !ch.is_live {
                        self.status_message = "Channel is not live".to_string();
                        return None;
                    }
                    if self.is_channel_recording(&ch.id) {
                        self.status_message = format!("Already recording {}", ch.display_name);
                        return None;
                    }
                    if ch.platform != PlatformKind::YouTube {
                        self.status_message = "Record from start is only supported for YouTube".to_string();
                        return None;
                    }
                    let ch = ch.clone();
                    return Some(AppAction::StartRecording {
                        channel_id: ch.id,
                        channel_name: ch.name,
                        platform: ch.platform,
                        transcode: self.transcode_mode,
                        from_start: true,
                    });
                }
            }
            KeyCode::Char('w') => {
                // Watch in mpv
                if let Some(ch) = self.selected_channel() {
                    if !ch.is_live {
                        self.status_message = "Channel is not live".to_string();
                        return None;
                    }
                    let ch = ch.clone();
                    self.watching_channel = Some(ch.name.clone());
                    return Some(AppAction::Watch {
                        channel_name: ch.name,
                        platform: ch.platform,
                    });
                }
            }
            KeyCode::Char('a') => {
                // Toggle auto-record
                if let Some(idx) = self.channels.get(self.selected_channel).map(|_| self.selected_channel) {
                    let ch = &mut self.channels[idx];
                    ch.auto_record = !ch.auto_record;

                    if ch.auto_record {
                        self.config.auto_record_channels.push(
                            crate::config::AutoRecordEntry {
                                platform: ch.platform.to_string(),
                                channel_id: ch.id.clone(),
                                channel_name: ch.name.clone(),
                                format: None,
                            },
                        );
                        self.status_message =
                            format!("Monitor ON for {}", ch.display_name);
                    } else {
                        self.config.auto_record_channels.retain(|a| {
                            !(a.channel_id == ch.id
                                && a.platform == ch.platform.to_string())
                        });
                        self.status_message =
                            format!("Monitor OFF for {}", ch.display_name);
                    }

                    self.rebuild_sidebar_order();

                    // Persist config
                    if let Err(e) = self.config.save(None) {
                        self.status_message = format!("Failed to save config: {e}");
                    }
                }
            }
            KeyCode::Char('t') => {
                self.transcode_mode = !self.transcode_mode;
                self.config.recording.transcode = self.transcode_mode;
                if let Err(e) = self.config.save(None) {
                    self.status_message = format!("Failed to save transcode toggle: {e}");
                } else {
                    self.status_message = if self.transcode_mode {
                        "Transcode mode: ON (NVENC) · saved".to_string()
                    } else {
                        "Transcode mode: OFF (passthrough) · saved".to_string()
                    };
                }
            }
            _ => {}
        }
        None
    }

    fn handle_recording_list_key(
        &mut self,
        key: crossterm::event::KeyEvent,
    ) -> Option<AppAction> {
        use crossterm::event::KeyCode;

        let recordings = self.sorted_recordings();
        let count = recordings.len();

        // Clamp selection to valid range
        if count > 0 {
            self.selected_recording = self.selected_recording.min(count - 1);
        }

        match key.code {
            KeyCode::Esc if !self.search_query.is_empty() => {
                self.clear_search();
            }
            KeyCode::Esc | KeyCode::Char('h') | KeyCode::Left => {
                self.active_pane = ActivePane::Sidebar;
            }
            KeyCode::Char('j') | KeyCode::Down => {
                if count > 0 {
                    self.selected_recording = (self.selected_recording + 1) % count;
                    self.remember_recording_selection();
                }
            }
            KeyCode::Char('k') | KeyCode::Up => {
                if count > 0 {
                    self.selected_recording = if self.selected_recording == 0 {
                        count - 1
                    } else {
                        self.selected_recording - 1
                    };
                    self.remember_recording_selection();
                }
            }
            KeyCode::Char('g') | KeyCode::Home => {
                if count > 0 {
                    self.selected_recording = 0;
                    self.remember_recording_selection();
                }
            }
            KeyCode::Char('G') | KeyCode::End => {
                if count > 0 {
                    self.selected_recording = count - 1;
                    self.remember_recording_selection();
                }
            }
            KeyCode::Char('s') => {
                // Stop selected recording
                let recs = self.sorted_recordings();
                if let Some(rec) = recs.get(self.selected_recording) {
                    if rec.state == RecordingState::Recording
                        || rec.state == RecordingState::ResolvingUrl
                    {
                        let job_id = rec.id;
                        self.send_recording_command(RecordingCommand::Stop { job_id });
                        self.status_message = format!("Stopping recording: {}", rec.channel_name);
                    }
                }
            }
            KeyCode::Char('p') => {
                // Play finished recording
                let recs = self.sorted_recordings();
                if let Some(rec) = recs.get(self.selected_recording) {
                    if rec.state == RecordingState::Finished {
                        let job_id = rec.id;
                        let path = rec.output_path.clone();
                        // Mark as watched (in-memory + persisted).
                        if let Some(job) = self.recordings.get_mut(&job_id) {
                            job.watched = true;
                        }
                        self.watched_history.insert(job_id);
                        crate::recording::watch_history::save(&self.watched_history);
                        return Some(AppAction::PlayFile { path });
                    }
                }
            }
            KeyCode::Char('i') => {
                // Show recording properties modal
                let recs = self.sorted_recordings();
                if let Some(rec) = recs.get(self.selected_recording) {
                    let job_id = rec.id;
                    let path = rec.output_path.clone();
                    self.show_properties = Some(job_id);
                    if !self.media_info_cache.contains_key(&job_id) {
                        return Some(AppAction::ProbeMedia { job_id, path });
                    }
                }
            }
            KeyCode::Char('v') => {
                // Toggle multi-select on the current row (insertion-ordered,
                // dedup via parallel set — yazi pattern).
                let recs = self.sorted_recordings();
                if let Some(rec) = recs.get(self.selected_recording) {
                    let id = rec.id;
                    if self.recording_selections_set.remove(&id) {
                        self.recording_selections_order.retain(|x| *x != id);
                    } else {
                        self.recording_selections_set.insert(id);
                        self.recording_selections_order.push(id);
                    }
                }
            }
            KeyCode::Char('V') => {
                self.recording_selections_order.clear();
                self.recording_selections_set.clear();
            }
            KeyCode::Char('D') => {
                // Delete to trash. Defaults to the current row when no
                // multi-select is active.
                let mut targets: Vec<Uuid> = if self.recording_selections_order.is_empty() {
                    let recs = self.sorted_recordings();
                    recs.get(self.selected_recording).map(|r| r.id).into_iter().collect()
                } else {
                    self.recording_selections_order.clone()
                };
                if targets.is_empty() {
                    return None;
                }
                // Refuse to trash anything still being written.
                targets.retain(|id| {
                    self.recordings
                        .get(id)
                        .map(|j| {
                            !matches!(
                                j.state,
                                RecordingState::Recording | RecordingState::ResolvingUrl
                            )
                        })
                        .unwrap_or(false)
                });

                let mut trashed = 0usize;
                let mut errors = 0usize;
                for id in &targets {
                    if let Some(job) = self.recordings.get(id) {
                        match crate::recording::trash::move_to_trash(&job.output_path) {
                            Ok(new_path) => {
                                tracing::info!(
                                    job_id = %id,
                                    new_path = %new_path.display(),
                                    "recording moved to trash"
                                );
                                trashed += 1;
                            }
                            Err(e) => {
                                tracing::warn!(job_id = %id, error = %e, "trash failed");
                                errors += 1;
                            }
                        }
                    }
                }
                // Drop from in-memory state regardless of trash outcome —
                // if the file move failed the user can manually clean up;
                // the AppState entry pointing at a missing file is worse UX.
                for id in &targets {
                    self.recordings.remove(id);
                }
                self.recording_selections_order.clear();
                self.recording_selections_set.clear();
                self.rebuild_active_channels();
                self.rebuild_sidebar_order();
                self.reconcile_selected_recording();

                self.status_message = if errors == 0 {
                    format!("Trashed {trashed} recording(s)")
                } else {
                    format!("Trashed {trashed}, {errors} failed (see log)")
                };
            }
            _ => {}
        }
        None
    }

    fn handle_status_bar_key(
        &mut self,
        key: crossterm::event::KeyEvent,
    ) -> Option<AppAction> {
        use crossterm::event::KeyCode;
        use crate::tui::widgets::status_bar::configured_platforms;

        let platforms = configured_platforms(self);
        if platforms.is_empty() {
            self.active_pane = self.prev_pane.take().unwrap_or(ActivePane::Sidebar);
            return None;
        }

        match key.code {
            KeyCode::Char('l') | KeyCode::Right => {
                self.selected_indicator = (self.selected_indicator + 1) % platforms.len();
            }
            KeyCode::Char('h') | KeyCode::Left => {
                self.selected_indicator = if self.selected_indicator == 0 {
                    platforms.len() - 1
                } else {
                    self.selected_indicator - 1
                };
            }
            KeyCode::Enter => {
                if let Some(&kind) = platforms.get(self.selected_indicator) {
                    self.show_platform_debug = Some(kind);
                }
            }
            KeyCode::Esc => {
                self.active_pane = self.prev_pane.take().unwrap_or(ActivePane::Sidebar);
            }
            _ => {}
        }
        None
    }

    fn handle_settings_key(
        &mut self,
        key: crossterm::event::KeyEvent,
    ) -> Option<AppAction> {
        use crossterm::event::KeyCode;

        const SETTINGS_COUNT: usize = 6;
        match key.code {
            KeyCode::Esc | KeyCode::Char('h') | KeyCode::Left => {
                // Persist any config changes (e.g. theme) on pane exit
                if let Err(e) = self.config.save(None) {
                    self.status_message = format!("Failed to save config: {e}");
                }
                self.active_pane = ActivePane::Sidebar;
            }
            KeyCode::Char('j') | KeyCode::Down => {
                self.settings_selected = (self.settings_selected + 1) % SETTINGS_COUNT;
            }
            KeyCode::Char('k') | KeyCode::Up => {
                self.settings_selected = if self.settings_selected == 0 {
                    SETTINGS_COUNT - 1
                } else {
                    self.settings_selected - 1
                };
            }
            KeyCode::Home => {
                self.settings_selected = 0;
            }
            KeyCode::End => {
                self.settings_selected = SETTINGS_COUNT - 1;
            }
            KeyCode::Enter | KeyCode::Char(' ') => {
                match self.settings_selected {
                    2 => {
                        // Transcode Mode — toggle, persist immediately.
                        self.transcode_mode = !self.transcode_mode;
                        self.config.recording.transcode = self.transcode_mode;
                        if let Err(e) = self.config.save(None) {
                            self.status_message = format!("Failed to save transcode toggle: {e}");
                        } else {
                            self.status_message = if self.transcode_mode {
                                "Transcode mode: ON (NVENC) · saved".to_string()
                            } else {
                                "Transcode mode: OFF (passthrough) · saved".to_string()
                            };
                        }
                    }
                    3 => {
                        // Theme — cycle through available themes
                        let themes = crate::tui::theme::available_themes();
                        if !themes.is_empty() {
                            let current = crate::tui::theme::Theme::current_name();
                            let idx = themes.iter().position(|t| *t == current).unwrap_or(0);
                            let next = (idx + 1) % themes.len();
                            crate::tui::theme::Theme::set_with_overrides(
                                &themes[next],
                                self.config.theme.colors(),
                                self.config.theme.ansi(),
                            );
                            self.config.theme.set_name(themes[next].clone());
                            self.status_message = format!("Theme: {}", themes[next]);
                            // Config save deferred to pane exit (debounce).
                        }
                    }
                    _ => {
                        // Read-only rows — hint to edit config file
                        let path = crate::config::AppConfig::config_path();
                        self.status_message =
                            format!("Edit {} to change this setting", path.display());
                    }
                }
            }
            _ => {}
        }
        None
    }

    fn handle_log_key(
        &mut self,
        key: crossterm::event::KeyEvent,
    ) -> Option<AppAction> {
        use crossterm::event::KeyCode;

        match key.code {
            KeyCode::Esc | KeyCode::Char('h') | KeyCode::Left => {
                self.active_pane = ActivePane::Sidebar;
            }
            KeyCode::Char('j') | KeyCode::Down => {
                if self.log_scroll + 1 < self.log_lines.len() {
                    self.log_scroll += 1;
                    self.log_auto_scroll = false;
                }
            }
            KeyCode::Char('k') | KeyCode::Up => {
                self.log_scroll = self.log_scroll.saturating_sub(1);
                self.log_auto_scroll = false;
            }
            KeyCode::Char('G') | KeyCode::End => {
                // Jump to bottom, re-enable auto-scroll
                self.log_scroll = self.log_lines.len().saturating_sub(1);
                self.log_auto_scroll = true;
            }
            KeyCode::Char('g') | KeyCode::Home => {
                // Jump to top
                self.log_scroll = 0;
                self.log_auto_scroll = false;
            }
            KeyCode::PageDown => {
                self.log_scroll = (self.log_scroll + 30).min(
                    self.log_lines.len().saturating_sub(1),
                );
                self.log_auto_scroll = false;
            }
            KeyCode::PageUp => {
                self.log_scroll = self.log_scroll.saturating_sub(30);
                self.log_auto_scroll = false;
            }
            KeyCode::Char('c') => {
                // Clear log
                std::fs::write(&self.log_path, "").ok();
                self.log_lines.clear();
                self.log_scroll = 0;
                self.status_message = "Log cleared".to_string();
            }
            _ => {}
        }
        None
    }

    pub fn refresh_log(&mut self) {
        if let Ok(content) = std::fs::read_to_string(&self.log_path) {
            self.log_lines = content
                .lines()
                .rev()
                .take(1000)
                .map(String::from)
                .collect::<Vec<_>>()
                .into_iter()
                .rev()
                .collect();
            if self.log_auto_scroll {
                self.log_scroll = self.log_lines.len().saturating_sub(1);
            }
        }
    }

    pub fn selected_channel(&self) -> Option<&ChannelEntry> {
        self.channels.get(self.selected_channel)
    }

    /// Navigate channels using sidebar_order (shared by sidebar and detail panes).
    /// When a search filter is active, only navigates through matching channels.
    fn navigate_channel(&mut self, forward: bool) {
        let nav_list = if !self.search_query.is_empty() && !self.search_filtered_channels.is_empty() {
            &self.search_filtered_channels
        } else {
            &self.sidebar_order
        };
        if nav_list.is_empty() {
            return;
        }
        let cur = nav_list
            .iter()
            .position(|&i| i == self.selected_channel)
            .unwrap_or(0);
        let len = nav_list.len();
        let next = if forward {
            (cur + 1) % len
        } else {
            if cur == 0 { len - 1 } else { cur - 1 }
        };
        self.selected_channel = nav_list[next];
    }

    fn jump_channel_to(&mut self, first: bool) {
        let nav_list = if !self.search_query.is_empty() && !self.search_filtered_channels.is_empty()
        {
            &self.search_filtered_channels
        } else {
            &self.sidebar_order
        };
        if nav_list.is_empty() {
            return;
        }
        self.selected_channel = if first {
            nav_list[0]
        } else {
            nav_list[nav_list.len() - 1]
        };
    }

    /// Rebuild the sidebar display order (call when channels or recording state changes)
    pub fn rebuild_sidebar_order(&mut self) {
        let mut twitch_indices: Vec<usize> = Vec::new();
        let mut youtube_indices: Vec<usize> = Vec::new();
        let mut patreon_indices: Vec<usize> = Vec::new();

        for (i, ch) in self.channels.iter().enumerate() {
            match ch.platform {
                PlatformKind::Twitch => twitch_indices.push(i),
                PlatformKind::YouTube => youtube_indices.push(i),
                PlatformKind::Patreon => patreon_indices.push(i),
            }
        }

        let sort_key = |idx: &usize| -> u8 {
            let ch = &self.channels[*idx];
            if self.is_channel_recording(&ch.id) {
                0
            } else if ch.is_live {
                1
            } else {
                2
            }
        };

        twitch_indices.sort_by_key(sort_key);
        youtube_indices.sort_by_key(sort_key);
        patreon_indices.sort_by_key(sort_key);

        self.sidebar_order = twitch_indices
            .iter()
            .chain(youtube_indices.iter())
            .chain(patreon_indices.iter())
            .copied()
            .collect();
    }

    /// Rebuild the set of channel_ids with active recordings
    fn rebuild_active_channels(&mut self) {
        self.active_recording_channels = self
            .recordings
            .values()
            .filter(|r| matches!(r.state, RecordingState::Recording | RecordingState::ResolvingUrl))
            .map(|r| r.channel_id.clone())
            .collect();
    }

    /// Check if a channel has an active recording
    pub fn is_channel_recording(&self, channel_id: &str) -> bool {
        self.active_recording_channels.contains(channel_id)
    }

    /// Update search filter results based on current query.
    pub fn update_search_filter(&mut self) {
        if self.search_query.is_empty() {
            self.search_filtered_channels.clear();
            self.search_filtered_recordings.clear();
            return;
        }

        let query = self.search_query.to_lowercase();

        // Filter channels: fuzzy subsequence match on display_name or name
        self.search_filtered_channels = self
            .sidebar_order
            .iter()
            .copied()
            .filter(|&i| {
                if let Some(ch) = self.channels.get(i) {
                    let haystack = ch.display_name.to_lowercase();
                    let name_lower = ch.name.to_lowercase();
                    haystack.contains(&query)
                        || name_lower.contains(&query)
                        || fuzzy_subsequence(&query, &haystack)
                        || fuzzy_subsequence(&query, &name_lower)
                } else {
                    false
                }
            })
            .collect();

        // Filter recordings: match channel_name or stream_title
        self.search_filtered_recordings = self
            .recordings
            .iter()
            .filter(|(_, rec)| {
                let haystack = format!(
                    "{} {}",
                    rec.channel_name,
                    rec.stream_title.as_deref().unwrap_or(""),
                )
                .to_lowercase();
                haystack.contains(&query) || fuzzy_subsequence(&query, &haystack)
            })
            .map(|(id, _)| *id)
            .collect();

        // If current selection is filtered out, jump to first visible
        if !self.search_filtered_channels.is_empty()
            && !self.search_filtered_channels.contains(&self.selected_channel)
        {
            self.selected_channel = self.search_filtered_channels[0];
        }
    }

    /// Clear search state.
    pub fn clear_search(&mut self) {
        self.search_active = false;
        self.search_query.clear();
        self.search_cursor = 0;
        self.search_filtered_channels.clear();
        self.search_filtered_recordings.clear();
    }

    /// Returns true if a channel index passes the current search filter.
    pub fn channel_matches_filter(&self, idx: usize) -> bool {
        if self.search_query.is_empty() {
            return true;
        }
        self.search_filtered_channels.contains(&idx)
    }

    /// Returns true if a recording job ID passes the current search filter.
    pub fn recording_matches_filter(&self, job_id: &Uuid) -> bool {
        if self.search_query.is_empty() {
            return true;
        }
        self.search_filtered_recordings.contains(job_id)
    }
}

use crate::search::fuzzy_subsequence;

/// Actions the TUI loop should execute in response to key events
pub enum AppAction {
    StartRecording {
        channel_id: String,
        channel_name: String,
        platform: PlatformKind,
        transcode: bool,
        from_start: bool,
    },
    Watch {
        channel_name: String,
        platform: PlatformKind,
    },
    LaunchMpv {
        channel_name: String,
        url: String,
    },
    PlayFile {
        path: PathBuf,
    },
    Notify {
        title: String,
        body: String,
    },
    SpawnPluginTask {
        plugin_name: &'static str,
        future: std::pin::Pin<Box<dyn std::future::Future<Output = Box<dyn std::any::Any + Send>> + Send>>,
    },
    ProbeMedia {
        job_id: Uuid,
        path: PathBuf,
    },
    /// Open a URL in the user's default browser. Used by the setup wizard
    /// to jump straight to device-code verification pages.
    OpenUrl {
        url: String,
    },
}

/// Process plugin actions, applying state mutations to app and registry.
/// Returns the last AppAction-producing action (if any).
pub fn process_plugin_actions(
    actions: Vec<crate::plugin::PluginAction>,
    app: &mut AppState,
    registry: &mut crate::plugin::registry::PluginRegistry,
) -> Option<AppAction> {
    let mut result: Option<AppAction> = None;
    for action in actions {
        match action {
            crate::plugin::PluginAction::SetStatus(msg) => {
                app.status_message = msg;
            }
            crate::plugin::PluginAction::Notify { title, body } => {
                result = Some(AppAction::Notify { title, body });
            }
            crate::plugin::PluginAction::ActivatePane(pane_id) => {
                app.active_pane = ActivePane::Plugin(pane_id);
                registry.set_active_pane(Some(pane_id));
            }
            crate::plugin::PluginAction::NavigateBack => {
                app.active_pane = ActivePane::Sidebar;
                registry.set_active_pane(None);
            }
            crate::plugin::PluginAction::SpawnTask { plugin_name, future } => {
                result = Some(AppAction::SpawnPluginTask { plugin_name, future });
            }
            crate::plugin::PluginAction::PlayFile(path) => {
                result = Some(AppAction::PlayFile { path });
            }
            crate::plugin::PluginAction::UpdateConfig { plugin_name, config_update } => {
                match plugin_name {
                    "crunchr" => {
                        if let Ok(cfg) = config_update.downcast::<crate::config::CrunchrConfig>() {
                            app.config.crunchr = *cfg;
                        }
                    }
                    "archiver" => {
                        if let Ok(cfg) = config_update.downcast::<crate::config::ArchiverConfig>() {
                            app.config.archiver = *cfg;
                        }
                    }
                    _ => {
                        tracing::warn!("Unknown plugin config update: {plugin_name}");
                    }
                }
                if let Err(e) = app.config.save(None) {
                    tracing::error!("Failed to save config after plugin update: {e}");
                    app.status_message = format!("Config save failed: {e}");
                }
            }
        }
    }
    result
}
