use std::collections::{HashMap, HashSet};
use std::path::PathBuf;

use ratatui_image::picker::Picker;
use ratatui_image::protocol::StatefulProtocol;
use uuid::Uuid;

use crate::config::AppConfig;
use crate::platform::{ChannelEntry, PlatformKind};
use crate::recording::job::{RecordingJob, RecordingState};
use crate::recording::RecordingCommand;

/// Events generated by the daemon (serializable, cross the IPC boundary).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub enum DaemonEvent {
    ChannelsUpdated(Vec<ChannelEntry>),
    ChannelWentLive(ChannelEntry),
    ChannelWentOffline(ChannelEntry),
    StreamUrlResolved {
        channel_id: String,
        url: String,
    },
    RecordingStarted {
        job: RecordingJob,
    },
    RecordingProgress {
        job_id: Uuid,
        bytes_written: u64,
        duration_secs: f64,
    },
    RecordingFinished {
        job_id: Uuid,
        final_state: RecordingState,
        error: Option<String>,
    },
    Notification {
        title: String,
        body: String,
    },
    AllRecordingsStopped,
    DeviceCodeRequired {
        kind: PlatformKind,
        verification_uri: String,
        user_code: String,
    },
    PlatformAuthenticated {
        kind: PlatformKind,
    },
    PatreonPostFound {
        creator_name: String,
        post_title: String,
    },
    Error(String),
}

/// Events handled by the TUI application.
#[allow(dead_code)]
pub enum AppEvent {
    /// Events from the daemon
    Daemon(DaemonEvent),
    /// Keyboard input
    Key(crossterm::event::KeyEvent),
    /// Terminal resize
    Resize(u16, u16),
    /// Tick (frame timer)
    Tick,
    /// Thumbnail downloaded to disk
    ThumbnailReady {
        channel_id: String,
        path: PathBuf,
    },
    /// Thumbnail decoded into protocol state
    ThumbnailDecoded {
        channel_id: String,
        protocol: StatefulProtocol,
    },
    /// Watch stream URL resolved
    WatchResolved {
        channel_name: String,
        stream_url: String,
    },
    /// Watch stream URL resolution failed
    WatchFailed {
        error: String,
    },
}

// Convenience constructors so existing code that sends DaemonEvent variants
// through AppEvent doesn't need massive refactoring everywhere at once.
impl AppEvent {
    pub fn channels_updated(channels: Vec<ChannelEntry>) -> Self {
        Self::Daemon(DaemonEvent::ChannelsUpdated(channels))
    }
    pub fn channel_went_live(channel: ChannelEntry) -> Self {
        Self::Daemon(DaemonEvent::ChannelWentLive(channel))
    }
    pub fn channel_went_offline(channel: ChannelEntry) -> Self {
        Self::Daemon(DaemonEvent::ChannelWentOffline(channel))
    }
    pub fn recording_started(job: RecordingJob) -> Self {
        Self::Daemon(DaemonEvent::RecordingStarted { job })
    }
    pub fn recording_progress(job_id: Uuid, bytes_written: u64, duration_secs: f64) -> Self {
        Self::Daemon(DaemonEvent::RecordingProgress { job_id, bytes_written, duration_secs })
    }
    pub fn recording_finished(job_id: Uuid, final_state: RecordingState, error: Option<String>) -> Self {
        Self::Daemon(DaemonEvent::RecordingFinished { job_id, final_state, error })
    }
    pub fn notification(title: String, body: String) -> Self {
        Self::Daemon(DaemonEvent::Notification { title, body })
    }
    pub fn all_recordings_stopped() -> Self {
        Self::Daemon(DaemonEvent::AllRecordingsStopped)
    }
    pub fn device_code_required(kind: PlatformKind, verification_uri: String, user_code: String) -> Self {
        Self::Daemon(DaemonEvent::DeviceCodeRequired { kind, verification_uri, user_code })
    }
    pub fn platform_authenticated(kind: PlatformKind) -> Self {
        Self::Daemon(DaemonEvent::PlatformAuthenticated { kind })
    }
    pub fn stream_url_resolved(channel_id: String, url: String) -> Self {
        Self::Daemon(DaemonEvent::StreamUrlResolved { channel_id, url })
    }
    pub fn error(msg: String) -> Self {
        Self::Daemon(DaemonEvent::Error(msg))
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ActivePane {
    Sidebar,
    Detail,
    RecordingList,
    Settings,
    Log,
    Wizard,
}

pub struct AppState {
    pub config: AppConfig,
    pub channels: Vec<ChannelEntry>,
    pub selected_channel: usize,
    pub active_pane: ActivePane,
    pub should_quit: bool,
    pub quit_confirm: bool,
    pub status_message: String,
    pub show_help: bool,
    // Recording state
    pub recordings: HashMap<Uuid, RecordingJob>,
    pub active_recording_channels: HashSet<String>, // channel_ids with active recordings
    pub selected_recording: usize,
    pub transcode_mode: bool,

    // Playback
    pub watching_channel: Option<String>,

    // Platform connection status
    pub twitch_connected: bool,
    pub youtube_connected: bool,
    pub patreon_connected: bool,

    // Thumbnail cache (channel_id -> protocol state for rendering)
    pub thumbnail_cache: HashMap<String, PathBuf>,
    pub thumbnail_protocols: HashMap<String, StatefulProtocol>,
    pub picker: Option<Picker>,

    // Sender for recording commands (direct mode) or daemon messages (client mode)
    pub recording_tx: Option<tokio::sync::mpsc::UnboundedSender<RecordingCommand>>,
    pub daemon_tx: Option<tokio::sync::mpsc::UnboundedSender<crate::ipc::ClientMessage>>,

    // Settings edit state
    pub settings_selected: usize,

    // Log viewer state
    pub log_lines: Vec<String>,
    pub log_scroll: usize,
    pub log_auto_scroll: bool,
    pub log_path: PathBuf,

    // Pending device-code auth (platform, verification_uri, user_code)
    pub pending_auth: Option<(PlatformKind, String, String)>,

    // Sidebar display order: indices into app.channels in visual sort order
    pub sidebar_order: Vec<usize>,

    // Sidebar scroll offsets for autoscroll (channel index → text scroll offset)
    pub scroll_offsets: HashMap<usize, usize>,
    pub tick_counter: u64,
    // Track previously selected channel for resetting scroll offset
    prev_selected_channel: usize,

    // Search / filter state
    pub search_active: bool,
    pub search_query: String,
    /// Filtered sidebar indices (into app.channels). Empty = no filter active.
    pub search_filtered_channels: Vec<usize>,
    /// Filtered recording job IDs. Empty = no filter active.
    pub search_filtered_recordings: Vec<uuid::Uuid>,
}

impl AppState {
    pub fn new(config: AppConfig) -> Self {
        let first_run = config.twitch.is_none() && config.youtube.is_none();
        Self {
            config,
            channels: Vec::new(),
            selected_channel: 0,
            active_pane: if first_run {
                ActivePane::Wizard
            } else {
                ActivePane::Sidebar
            },
            should_quit: false,
            quit_confirm: false,
            status_message: String::new(),
            show_help: false,
            recordings: HashMap::new(),
            active_recording_channels: HashSet::new(),
            selected_recording: 0,
            transcode_mode: false,
            watching_channel: None,
            twitch_connected: false,
            youtube_connected: false,
            patreon_connected: false,
            thumbnail_cache: HashMap::new(),
            thumbnail_protocols: HashMap::new(),
            picker: {
                let (tx, rx) = std::sync::mpsc::channel();
                std::thread::spawn(move || {
                    let _ = tx.send(Picker::from_query_stdio().ok());
                });
                rx.recv_timeout(std::time::Duration::from_millis(500))
                    .ok()
                    .flatten()
            },
            recording_tx: None,
            daemon_tx: None,
            settings_selected: 0,
            log_lines: Vec::new(),
            log_scroll: 0,
            log_auto_scroll: true,
            log_path: AppConfig::state_dir().join("strivo.log"),
            pending_auth: None,
            sidebar_order: Vec::new(),
            scroll_offsets: HashMap::new(),
            tick_counter: 0,
            prev_selected_channel: 0,
            search_active: false,
            search_query: String::new(),
            search_filtered_channels: Vec::new(),
            search_filtered_recordings: Vec::new(),
        }
    }

    /// Send a recording command through the appropriate channel (direct or daemon).
    pub fn send_recording_command(&self, cmd: RecordingCommand) {
        if let Some(ref tx) = self.daemon_tx {
            let _ = tx.send(crate::ipc::ClientMessage::Recording(cmd));
        } else if let Some(ref tx) = self.recording_tx {
            let _ = tx.send(cmd);
        }
    }

    pub fn active_recording_count(&self) -> usize {
        self.recordings
            .values()
            .filter(|r| {
                r.state == RecordingState::Recording || r.state == RecordingState::ResolvingUrl
            })
            .count()
    }

    pub fn sorted_recordings(&self) -> Vec<&RecordingJob> {
        let mut recs: Vec<&RecordingJob> = self.recordings.values().collect();
        recs.sort_by(|a, b| b.started_at.cmp(&a.started_at));
        recs
    }

    /// Groups finished+active recordings by day label ("Today", "Yesterday", "March 12, 2026"), newest first
    pub fn recordings_by_day(&self) -> Vec<(String, Vec<&RecordingJob>)> {
        use chrono::Local;

        let mut recs = self.sorted_recordings();
        // sorted_recordings already sorts newest first
        if recs.is_empty() {
            return Vec::new();
        }

        let today = Local::now().date_naive();
        let yesterday = today - chrono::Duration::days(1);

        let mut groups: Vec<(String, Vec<&RecordingJob>)> = Vec::new();

        for rec in recs.drain(..) {
            let rec_date = rec.started_at.with_timezone(&Local).date_naive();
            let label = if rec_date == today {
                "Today".to_string()
            } else if rec_date == yesterday {
                "Yesterday".to_string()
            } else {
                rec_date.format("%B %-d, %Y").to_string()
            };

            if let Some(last) = groups.last_mut() {
                if last.0 == label {
                    last.1.push(rec);
                    continue;
                }
            }
            groups.push((label, vec![rec]));
        }

        groups
    }

    /// Counts finished recordings where `watched == false` for a given channel
    pub fn unwatched_count_for_channel(&self, channel_id: &str) -> usize {
        self.recordings
            .values()
            .filter(|r| {
                r.channel_id == channel_id
                    && r.state == RecordingState::Finished
                    && !r.watched
            })
            .count()
    }

    pub fn handle_event(&mut self, event: AppEvent) -> Option<AppAction> {
        match event {
            AppEvent::Key(key) => return self.handle_key(key),
            AppEvent::Resize(_, _) => {}
            AppEvent::Tick => {
                self.tick_counter = self.tick_counter.wrapping_add(1);
                // Reset scroll offset when selection changes
                if self.selected_channel != self.prev_selected_channel {
                    self.scroll_offsets.remove(&self.prev_selected_channel);
                    self.prev_selected_channel = self.selected_channel;
                }
                // Autoscroll stream title for selected live channel in sidebar
                if self.active_pane == ActivePane::Sidebar {
                    if let Some(ch) = self.channels.get(self.selected_channel) {
                        if ch.is_live && ch.stream_title.is_some() {
                            if self.tick_counter % 6 == 0 {
                                let offset = self.scroll_offsets.entry(self.selected_channel).or_insert(0);
                                *offset += 1;
                            }
                        }
                    }
                }
            }
            AppEvent::ThumbnailReady { channel_id, path } => {
                self.thumbnail_cache.insert(channel_id.clone(), path);
            }
            AppEvent::ThumbnailDecoded { channel_id, protocol } => {
                self.thumbnail_protocols.insert(channel_id, protocol);
            }
            AppEvent::WatchResolved { channel_name, stream_url } => {
                self.watching_channel = Some(channel_name.clone());
                return Some(AppAction::LaunchMpv {
                    channel_name,
                    url: stream_url,
                });
            }
            AppEvent::WatchFailed { error } => {
                self.status_message = format!("Watch failed: {error}");
            }
            AppEvent::Daemon(de) => return self.handle_daemon_event(de),
        }
        None
    }

    pub fn handle_daemon_event(&mut self, event: DaemonEvent) -> Option<AppAction> {
        match event {
            DaemonEvent::ChannelsUpdated(channels) => {
                // Remember currently selected channel by ID
                let prev_selected_id = self.channels.get(self.selected_channel).map(|ch| ch.id.clone());

                // Preserve auto_record settings from config
                let mut updated = channels;
                for ch in &mut updated {
                    ch.auto_record = self.config.auto_record_channels.iter().any(|a| {
                        a.channel_id == ch.id && a.platform == ch.platform.to_string()
                    });
                }
                self.channels = updated;

                // Restore selection by ID, fall back to clamping
                if let Some(ref prev_id) = prev_selected_id {
                    if let Some(new_idx) = self.channels.iter().position(|ch| &ch.id == prev_id) {
                        self.selected_channel = new_idx;
                    } else if self.selected_channel >= self.channels.len() {
                        self.selected_channel = self.channels.len().saturating_sub(1);
                    }
                } else if self.selected_channel >= self.channels.len() {
                    self.selected_channel = self.channels.len().saturating_sub(1);
                }

                // Prune stale thumbnail entries
                let current_ids: HashSet<String> = self.channels.iter().map(|ch| ch.id.clone()).collect();
                self.thumbnail_cache.retain(|id, _| current_ids.contains(id));
                self.thumbnail_protocols.retain(|id, _| current_ids.contains(id));

                self.rebuild_sidebar_order();
            }
            DaemonEvent::ChannelWentLive(ref channel) => {
                self.status_message = format!("{} went live!", channel.display_name);
                return Some(AppAction::Notify {
                    title: format!("{} is live!", channel.display_name),
                    body: channel
                        .stream_title
                        .clone()
                        .unwrap_or_else(|| "Stream started".to_string()),
                });
            }
            DaemonEvent::ChannelWentOffline(channel) => {
                self.status_message = format!("{} went offline", channel.display_name);
            }
            DaemonEvent::StreamUrlResolved { channel_id, .. } => {
                self.status_message = format!("Stream URL resolved for {channel_id}");
            }
            DaemonEvent::RecordingStarted { job } => {
                self.status_message = format!("Recording started: {}", job.channel_name);
                self.recordings.insert(job.id, job);
                self.rebuild_active_channels();
                self.rebuild_sidebar_order();
            }
            DaemonEvent::RecordingProgress {
                job_id,
                bytes_written,
                duration_secs,
            } => {
                if let Some(job) = self.recordings.get_mut(&job_id) {
                    job.bytes_written = bytes_written;
                    job.duration_secs = duration_secs;
                    job.state = RecordingState::Recording;
                }
            }
            DaemonEvent::RecordingFinished { job_id, final_state, error } => {
                if let Some(job) = self.recordings.get_mut(&job_id) {
                    job.state = final_state;
                    job.error = error;
                }
                self.rebuild_active_channels();
                self.rebuild_sidebar_order();
                let active = self.active_recording_count();
                self.status_message = format!("Recording finished ({active} active)");
            }
            DaemonEvent::Notification { title, body } => {
                return Some(AppAction::Notify { title, body });
            }
            DaemonEvent::AllRecordingsStopped => {
                self.should_quit = true;
            }
            DaemonEvent::DeviceCodeRequired { kind, verification_uri, user_code } => {
                self.status_message = format!(
                    "{kind} auth: go to {verification_uri} and enter code: {user_code}"
                );
                self.pending_auth = Some((kind, verification_uri, user_code));
            }
            DaemonEvent::PlatformAuthenticated { kind } => {
                match kind {
                    PlatformKind::Twitch => self.twitch_connected = true,
                    PlatformKind::YouTube => self.youtube_connected = true,
                    PlatformKind::Patreon => self.patreon_connected = true,
                }
                self.status_message = format!("{kind} connected");
                self.pending_auth = None;
            }
            DaemonEvent::PatreonPostFound { creator_name, post_title } => {
                self.status_message = format!("Patreon: {creator_name} posted '{post_title}'");
            }
            DaemonEvent::Error(msg) => {
                self.status_message = format!("Error: {msg}");
            }
        }
        None
    }

    fn handle_key(&mut self, key: crossterm::event::KeyEvent) -> Option<AppAction> {
        use crossterm::event::{KeyCode, KeyEventKind};

        if key.kind != KeyEventKind::Press {
            return None;
        }

        // Search mode input handling — intercept all keys
        if self.search_active {
            match key.code {
                KeyCode::Esc => {
                    self.clear_search();
                }
                KeyCode::Enter => {
                    // Confirm filter and exit search input mode (filter stays active)
                    self.search_active = false;
                    if self.search_query.is_empty() {
                        self.clear_search();
                    }
                }
                KeyCode::Backspace => {
                    self.search_query.pop();
                    self.update_search_filter();
                }
                KeyCode::Char(c) => {
                    self.search_query.push(c);
                    self.update_search_filter();
                }
                _ => {}
            }
            return None;
        }

        // Quit confirmation handling
        if self.quit_confirm {
            match key.code {
                KeyCode::Char('y') | KeyCode::Char('Y') => {
                    // Stop all recordings — quit will happen when AllRecordingsStopped arrives
                    self.send_recording_command(RecordingCommand::StopAll);
                    self.status_message = "Stopping recordings...".to_string();
                    self.quit_confirm = false;
                    return None;
                }
                KeyCode::Char('n') | KeyCode::Char('N') | KeyCode::Esc => {
                    self.quit_confirm = false;
                    self.status_message.clear();
                    return None;
                }
                _ => return None,
            }
        }

        // Global keys
        match key.code {
            KeyCode::Char('q') if self.active_pane != ActivePane::Wizard => {
                if self.active_recording_count() > 0 {
                    self.quit_confirm = true;
                    self.status_message =
                        "Recordings active! Quit? (y/n)".to_string();
                } else {
                    self.should_quit = true;
                }
                return None;
            }
            KeyCode::Char('?') => {
                self.show_help = !self.show_help;
                return None;
            }
            KeyCode::Esc if self.show_help => {
                self.show_help = false;
                return None;
            }
            KeyCode::Esc if self.active_pane == ActivePane::Wizard => {
                self.active_pane = ActivePane::Sidebar;
                return None;
            }
            KeyCode::Char('F') if self.active_pane != ActivePane::Wizard && self.active_pane != ActivePane::Log => {
                self.refresh_log();
                self.active_pane = ActivePane::Log;
                return None;
            }
            KeyCode::Char('/') if matches!(self.active_pane, ActivePane::Sidebar | ActivePane::RecordingList | ActivePane::Detail) => {
                self.search_active = true;
                self.search_query.clear();
                self.search_filtered_channels.clear();
                self.search_filtered_recordings.clear();
                return None;
            }
            _ => {}
        }

        match self.active_pane {
            ActivePane::Sidebar => self.handle_sidebar_key(key),
            ActivePane::Detail => self.handle_detail_key(key),
            ActivePane::RecordingList => self.handle_recording_list_key(key),
            ActivePane::Settings => self.handle_settings_key(key),
            ActivePane::Log => self.handle_log_key(key),
            ActivePane::Wizard => None,
        }
    }

    fn handle_sidebar_key(
        &mut self,
        key: crossterm::event::KeyEvent,
    ) -> Option<AppAction> {
        use crossterm::event::KeyCode;

        match key.code {
            KeyCode::Esc if !self.search_query.is_empty() => {
                self.clear_search();
            }
            KeyCode::Char('j') | KeyCode::Down => {
                self.navigate_channel(true);
            }
            KeyCode::Char('k') | KeyCode::Up => {
                self.navigate_channel(false);
            }
            KeyCode::Enter | KeyCode::Right | KeyCode::Char('l') => {
                if !self.channels.is_empty() {
                    self.active_pane = ActivePane::Detail;
                }
            }
            KeyCode::Char('L') => {
                self.active_pane = ActivePane::RecordingList;
            }
            KeyCode::Char('s') | KeyCode::Char('C') => {
                self.active_pane = ActivePane::Settings;
            }
            _ => {}
        }
        None
    }

    fn handle_detail_key(
        &mut self,
        key: crossterm::event::KeyEvent,
    ) -> Option<AppAction> {
        use crossterm::event::KeyCode;

        match key.code {
            KeyCode::Esc if !self.search_query.is_empty() => {
                self.clear_search();
            }
            KeyCode::Esc | KeyCode::Char('h') | KeyCode::Left => {
                self.active_pane = ActivePane::Sidebar;
            }
            KeyCode::Char('j') | KeyCode::Down => {
                self.navigate_channel(true);
            }
            KeyCode::Char('k') | KeyCode::Up => {
                self.navigate_channel(false);
            }
            KeyCode::Char('r') => {
                // Start recording
                if let Some(ch) = self.selected_channel() {
                    if !ch.is_live {
                        self.status_message = "Channel is not live".to_string();
                        return None;
                    }
                    if self.is_channel_recording(&ch.id) {
                        self.status_message = format!("Already recording {}", ch.display_name);
                        return None;
                    }
                    let ch = ch.clone();
                    return Some(AppAction::StartRecording {
                        channel_id: ch.id,
                        channel_name: ch.name,
                        platform: ch.platform,
                        transcode: self.transcode_mode,
                        from_start: false,
                    });
                }
            }
            KeyCode::Char('R') => {
                // Record from start (YouTube only — uses yt-dlp --live-from-start)
                if let Some(ch) = self.selected_channel() {
                    if !ch.is_live {
                        self.status_message = "Channel is not live".to_string();
                        return None;
                    }
                    if self.is_channel_recording(&ch.id) {
                        self.status_message = format!("Already recording {}", ch.display_name);
                        return None;
                    }
                    if ch.platform != PlatformKind::YouTube {
                        self.status_message = "Record from start is only supported for YouTube".to_string();
                        return None;
                    }
                    let ch = ch.clone();
                    return Some(AppAction::StartRecording {
                        channel_id: ch.id,
                        channel_name: ch.name,
                        platform: ch.platform,
                        transcode: self.transcode_mode,
                        from_start: true,
                    });
                }
            }
            KeyCode::Char('w') => {
                // Watch in mpv
                if let Some(ch) = self.selected_channel() {
                    if !ch.is_live {
                        self.status_message = "Channel is not live".to_string();
                        return None;
                    }
                    let ch = ch.clone();
                    self.watching_channel = Some(ch.name.clone());
                    return Some(AppAction::Watch {
                        channel_name: ch.name,
                        platform: ch.platform,
                    });
                }
            }
            KeyCode::Char('a') => {
                // Toggle auto-record
                if let Some(idx) = self.channels.get(self.selected_channel).map(|_| self.selected_channel) {
                    let ch = &mut self.channels[idx];
                    ch.auto_record = !ch.auto_record;

                    if ch.auto_record {
                        self.config.auto_record_channels.push(
                            crate::config::AutoRecordEntry {
                                platform: ch.platform.to_string(),
                                channel_id: ch.id.clone(),
                                channel_name: ch.name.clone(),
                            },
                        );
                        self.status_message =
                            format!("Monitor ON for {}", ch.display_name);
                    } else {
                        self.config.auto_record_channels.retain(|a| {
                            !(a.channel_id == ch.id
                                && a.platform == ch.platform.to_string())
                        });
                        self.status_message =
                            format!("Monitor OFF for {}", ch.display_name);
                    }

                    self.rebuild_sidebar_order();

                    // Persist config
                    if let Err(e) = self.config.save(None) {
                        self.status_message = format!("Failed to save config: {e}");
                    }
                }
            }
            KeyCode::Char('t') => {
                self.transcode_mode = !self.transcode_mode;
                self.status_message = if self.transcode_mode {
                    "Transcode mode: ON (NVENC)".to_string()
                } else {
                    "Transcode mode: OFF (passthrough)".to_string()
                };
            }
            _ => {}
        }
        None
    }

    fn handle_recording_list_key(
        &mut self,
        key: crossterm::event::KeyEvent,
    ) -> Option<AppAction> {
        use crossterm::event::KeyCode;

        let recordings = self.sorted_recordings();
        let count = recordings.len();

        // Clamp selection to valid range
        if count > 0 {
            self.selected_recording = self.selected_recording.min(count - 1);
        }

        match key.code {
            KeyCode::Esc if !self.search_query.is_empty() => {
                self.clear_search();
            }
            KeyCode::Esc | KeyCode::Char('h') | KeyCode::Left => {
                self.active_pane = ActivePane::Sidebar;
            }
            KeyCode::Char('j') | KeyCode::Down => {
                if count > 0 {
                    self.selected_recording = (self.selected_recording + 1) % count;
                }
            }
            KeyCode::Char('k') | KeyCode::Up => {
                if count > 0 {
                    self.selected_recording = if self.selected_recording == 0 {
                        count - 1
                    } else {
                        self.selected_recording - 1
                    };
                }
            }
            KeyCode::Char('s') => {
                // Stop selected recording
                let recs = self.sorted_recordings();
                if let Some(rec) = recs.get(self.selected_recording) {
                    if rec.state == RecordingState::Recording
                        || rec.state == RecordingState::ResolvingUrl
                    {
                        let job_id = rec.id;
                        self.send_recording_command(RecordingCommand::Stop { job_id });
                        self.status_message = format!("Stopping recording: {}", rec.channel_name);
                    }
                }
            }
            KeyCode::Char('p') => {
                // Play finished recording
                let recs = self.sorted_recordings();
                if let Some(rec) = recs.get(self.selected_recording) {
                    if rec.state == RecordingState::Finished {
                        let job_id = rec.id;
                        let path = rec.output_path.clone();
                        // Mark as watched
                        if let Some(job) = self.recordings.get_mut(&job_id) {
                            job.watched = true;
                        }
                        return Some(AppAction::PlayFile { path });
                    }
                }
            }
            _ => {}
        }
        None
    }

    fn handle_settings_key(
        &mut self,
        key: crossterm::event::KeyEvent,
    ) -> Option<AppAction> {
        use crossterm::event::KeyCode;

        const SETTINGS_COUNT: usize = 6;
        match key.code {
            KeyCode::Esc | KeyCode::Char('h') | KeyCode::Left => {
                // Persist any config changes (e.g. theme) on pane exit
                if let Err(e) = self.config.save(None) {
                    self.status_message = format!("Failed to save config: {e}");
                }
                self.active_pane = ActivePane::Sidebar;
            }
            KeyCode::Char('j') | KeyCode::Down => {
                self.settings_selected = (self.settings_selected + 1) % SETTINGS_COUNT;
            }
            KeyCode::Char('k') | KeyCode::Up => {
                self.settings_selected = if self.settings_selected == 0 {
                    SETTINGS_COUNT - 1
                } else {
                    self.settings_selected - 1
                };
            }
            KeyCode::Enter | KeyCode::Char(' ') => {
                // Theme row (index 3) — cycle through available themes
                if self.settings_selected == 3 {
                    let themes = crate::tui::theme::available_themes();
                    if !themes.is_empty() {
                        let current = crate::tui::theme::Theme::current_name();
                        let idx = themes.iter().position(|t| *t == current).unwrap_or(0);
                        let next = (idx + 1) % themes.len();
                        crate::tui::theme::Theme::set(&themes[next]);
                        self.config.theme = themes[next].clone();
                        self.status_message = format!("Theme: {}", themes[next]);
                        // Config save deferred to pane exit (debounce)
                    }
                }
            }
            _ => {}
        }
        None
    }

    fn handle_log_key(
        &mut self,
        key: crossterm::event::KeyEvent,
    ) -> Option<AppAction> {
        use crossterm::event::KeyCode;

        match key.code {
            KeyCode::Esc | KeyCode::Char('h') | KeyCode::Left => {
                self.active_pane = ActivePane::Sidebar;
            }
            KeyCode::Char('j') | KeyCode::Down => {
                if self.log_scroll + 1 < self.log_lines.len() {
                    self.log_scroll += 1;
                    self.log_auto_scroll = false;
                }
            }
            KeyCode::Char('k') | KeyCode::Up => {
                self.log_scroll = self.log_scroll.saturating_sub(1);
                self.log_auto_scroll = false;
            }
            KeyCode::Char('G') => {
                // Jump to bottom, re-enable auto-scroll
                self.log_scroll = self.log_lines.len().saturating_sub(1);
                self.log_auto_scroll = true;
            }
            KeyCode::Char('g') => {
                // Jump to top
                self.log_scroll = 0;
                self.log_auto_scroll = false;
            }
            KeyCode::PageDown => {
                self.log_scroll = (self.log_scroll + 30).min(
                    self.log_lines.len().saturating_sub(1),
                );
                self.log_auto_scroll = false;
            }
            KeyCode::PageUp => {
                self.log_scroll = self.log_scroll.saturating_sub(30);
                self.log_auto_scroll = false;
            }
            KeyCode::Char('c') => {
                // Clear log
                std::fs::write(&self.log_path, "").ok();
                self.log_lines.clear();
                self.log_scroll = 0;
                self.status_message = "Log cleared".to_string();
            }
            _ => {}
        }
        None
    }

    pub fn refresh_log(&mut self) {
        if let Ok(content) = std::fs::read_to_string(&self.log_path) {
            self.log_lines = content
                .lines()
                .rev()
                .take(1000)
                .map(String::from)
                .collect::<Vec<_>>()
                .into_iter()
                .rev()
                .collect();
            if self.log_auto_scroll {
                self.log_scroll = self.log_lines.len().saturating_sub(1);
            }
        }
    }

    pub fn selected_channel(&self) -> Option<&ChannelEntry> {
        self.channels.get(self.selected_channel)
    }

    /// Navigate channels using sidebar_order (shared by sidebar and detail panes).
    /// When a search filter is active, only navigates through matching channels.
    fn navigate_channel(&mut self, forward: bool) {
        let nav_list = if !self.search_query.is_empty() && !self.search_filtered_channels.is_empty() {
            &self.search_filtered_channels
        } else {
            &self.sidebar_order
        };
        if nav_list.is_empty() {
            return;
        }
        let cur = nav_list
            .iter()
            .position(|&i| i == self.selected_channel)
            .unwrap_or(0);
        let len = nav_list.len();
        let next = if forward {
            (cur + 1) % len
        } else {
            if cur == 0 { len - 1 } else { cur - 1 }
        };
        self.selected_channel = nav_list[next];
    }

    /// Rebuild the sidebar display order (call when channels or recording state changes)
    pub fn rebuild_sidebar_order(&mut self) {
        let mut twitch_indices: Vec<usize> = Vec::new();
        let mut youtube_indices: Vec<usize> = Vec::new();
        let mut patreon_indices: Vec<usize> = Vec::new();

        for (i, ch) in self.channels.iter().enumerate() {
            match ch.platform {
                PlatformKind::Twitch => twitch_indices.push(i),
                PlatformKind::YouTube => youtube_indices.push(i),
                PlatformKind::Patreon => patreon_indices.push(i),
            }
        }

        let sort_key = |idx: &usize| -> u8 {
            let ch = &self.channels[*idx];
            if self.is_channel_recording(&ch.id) {
                0
            } else if ch.is_live {
                1
            } else {
                2
            }
        };

        twitch_indices.sort_by_key(sort_key);
        youtube_indices.sort_by_key(sort_key);
        patreon_indices.sort_by_key(sort_key);

        self.sidebar_order = twitch_indices
            .iter()
            .chain(youtube_indices.iter())
            .chain(patreon_indices.iter())
            .copied()
            .collect();
    }

    /// Rebuild the set of channel_ids with active recordings
    fn rebuild_active_channels(&mut self) {
        self.active_recording_channels = self
            .recordings
            .values()
            .filter(|r| matches!(r.state, RecordingState::Recording | RecordingState::ResolvingUrl))
            .map(|r| r.channel_id.clone())
            .collect();
    }

    /// Check if a channel has an active recording
    pub fn is_channel_recording(&self, channel_id: &str) -> bool {
        self.active_recording_channels.contains(channel_id)
    }

    /// Update search filter results based on current query.
    pub fn update_search_filter(&mut self) {
        if self.search_query.is_empty() {
            self.search_filtered_channels.clear();
            self.search_filtered_recordings.clear();
            return;
        }

        let query = self.search_query.to_lowercase();

        // Filter channels: fuzzy subsequence match on display_name or name
        self.search_filtered_channels = self
            .sidebar_order
            .iter()
            .copied()
            .filter(|&i| {
                if let Some(ch) = self.channels.get(i) {
                    let haystack = ch.display_name.to_lowercase();
                    let name_lower = ch.name.to_lowercase();
                    haystack.contains(&query)
                        || name_lower.contains(&query)
                        || fuzzy_subsequence(&query, &haystack)
                        || fuzzy_subsequence(&query, &name_lower)
                } else {
                    false
                }
            })
            .collect();

        // Filter recordings: match channel_name or stream_title
        self.search_filtered_recordings = self
            .recordings
            .iter()
            .filter(|(_, rec)| {
                let haystack = format!(
                    "{} {}",
                    rec.channel_name,
                    rec.stream_title.as_deref().unwrap_or(""),
                )
                .to_lowercase();
                haystack.contains(&query) || fuzzy_subsequence(&query, &haystack)
            })
            .map(|(id, _)| *id)
            .collect();

        // If current selection is filtered out, jump to first visible
        if !self.search_filtered_channels.is_empty()
            && !self.search_filtered_channels.contains(&self.selected_channel)
        {
            self.selected_channel = self.search_filtered_channels[0];
        }
    }

    /// Clear search state.
    pub fn clear_search(&mut self) {
        self.search_active = false;
        self.search_query.clear();
        self.search_filtered_channels.clear();
        self.search_filtered_recordings.clear();
    }

    /// Returns true if a channel index passes the current search filter.
    pub fn channel_matches_filter(&self, idx: usize) -> bool {
        if self.search_query.is_empty() {
            return true;
        }
        self.search_filtered_channels.contains(&idx)
    }

    /// Returns true if a recording job ID passes the current search filter.
    pub fn recording_matches_filter(&self, job_id: &Uuid) -> bool {
        if self.search_query.is_empty() {
            return true;
        }
        self.search_filtered_recordings.contains(job_id)
    }
}

use crate::search::fuzzy_subsequence;

/// Actions the TUI loop should execute in response to key events
pub enum AppAction {
    StartRecording {
        channel_id: String,
        channel_name: String,
        platform: PlatformKind,
        transcode: bool,
        from_start: bool,
    },
    Watch {
        channel_name: String,
        platform: PlatformKind,
    },
    LaunchMpv {
        channel_name: String,
        url: String,
    },
    PlayFile {
        path: PathBuf,
    },
    Notify {
        title: String,
        body: String,
    },
}
